"""Generated SDK endpoint manifest for AfroLete developer clients."""

# Generated by scripts/generate_sdk_endpoint_manifest.py; do not edit by hand.

from __future__ import annotations

from typing import Any

AFROLETE_SDK_ENDPOINTS: tuple[dict[str, Any], ...] = tuple([
  {
    "method": "GET",
    "path": "/sdk/me",
    "category": "auth",
    "summary": "Inspect the active API key, application, scopes, quota, and counter mode.",
    "required_scopes": [],
    "typescript_entry_point": "client.me",
    "python_entry_point": "client.me",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/organization",
    "category": "organization",
    "summary": "Read tenant organization identity, branding, contact, and platform metadata.",
    "required_scopes": [
      "read:organization"
    ],
    "typescript_entry_point": "client.organization.get",
    "python_entry_point": "client.organization.get",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/people",
    "category": "people",
    "summary": "Create or reuse tenant people for roster, guardian, and member imports.",
    "required_scopes": [
      "write:people",
      "write:roster"
    ],
    "typescript_entry_point": "client.people.create",
    "python_entry_point": "client.people.create",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/people/{athlete_person_id}/guardians",
    "category": "people",
    "summary": "Link parents or guardians to athlete records with consent authority flags.",
    "required_scopes": [
      "write:guardians",
      "write:roster"
    ],
    "typescript_entry_point": "client.people.linkGuardian",
    "python_entry_point": "client.people.link_guardian",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/people/{athlete_person_id}/consent-requests",
    "category": "people",
    "summary": "Create one-use guardian consent requests for events, teams, or organizations.",
    "required_scopes": [
      "write:consent",
      "write:guardians",
      "write:roster"
    ],
    "typescript_entry_point": "client.people.createConsentRequest",
    "python_entry_point": "client.people.create_consent_request",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/teams",
    "category": "teams",
    "summary": "List tenant teams for directory sync and roster targeting.",
    "required_scopes": [
      "read:organization",
      "read:teams"
    ],
    "typescript_entry_point": "client.teams.list",
    "python_entry_point": "client.teams.list",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/teams",
    "category": "teams",
    "summary": "Create tenant teams while preserving organization-team relationships.",
    "required_scopes": [
      "write:teams"
    ],
    "typescript_entry_point": "client.teams.create",
    "python_entry_point": "client.teams.create",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/teams/{team_id}/members",
    "category": "teams",
    "summary": "Assign existing people to team rosters and create athlete profiles as needed.",
    "required_scopes": [
      "write:roster",
      "write:teams"
    ],
    "typescript_entry_point": "client.teams.addMember",
    "python_entry_point": "client.teams.add_member",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/events",
    "category": "events",
    "summary": "List tenant events with optional team filtering.",
    "required_scopes": [
      "read:events",
      "write:events"
    ],
    "typescript_entry_point": "client.events.list",
    "python_entry_point": "client.events.list",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/events",
    "category": "events",
    "summary": "Create tenant schedule events from trusted partner systems.",
    "required_scopes": [
      "write:events"
    ],
    "typescript_entry_point": "client.events.create",
    "python_entry_point": "client.events.create",
    "webhook_events": [
      "events.created"
    ]
  },
  {
    "method": "GET",
    "path": "/sdk/events/{event_id}/attendance",
    "category": "attendance",
    "summary": "List attendance records for event kiosks and matchday sync.",
    "required_scopes": [
      "read:attendance",
      "write:attendance"
    ],
    "typescript_entry_point": "client.events.attendance.list",
    "python_entry_point": "client.events.attendance.list",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/events/{event_id}/attendance",
    "category": "attendance",
    "summary": "Record event attendance while preserving tenant policy gates.",
    "required_scopes": [
      "write:attendance"
    ],
    "typescript_entry_point": "client.events.attendance.record",
    "python_entry_point": "client.events.attendance.record",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/agents",
    "category": "ai_agents",
    "summary": "List tenant AI agents available to trusted integrations.",
    "required_scopes": [
      "read:agents",
      "write:agents"
    ],
    "typescript_entry_point": "client.agents.list",
    "python_entry_point": "client.agents.list",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/agents/tasks",
    "category": "ai_agents",
    "summary": "List governed AI-agent task status for integration handoff tracking.",
    "required_scopes": [
      "read:agents",
      "write:agents"
    ],
    "typescript_entry_point": "client.agents.tasks.list",
    "python_entry_point": "client.agents.tasks.list",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/agents/{agent_id}/tasks",
    "category": "ai_agents",
    "summary": "Queue governed AI-agent work from trusted external systems.",
    "required_scopes": [
      "write:agents"
    ],
    "typescript_entry_point": "client.agents.tasks.queue",
    "python_entry_point": "client.agents.tasks.queue",
    "webhook_events": [
      "agents.task.queued"
    ]
  },
  {
    "method": "GET",
    "path": "/sdk/communications/templates",
    "category": "communications",
    "summary": "List tenant communication templates.",
    "required_scopes": [
      "read:communications",
      "write:communications"
    ],
    "typescript_entry_point": "client.communications.templates.list",
    "python_entry_point": "client.communications.templates.list",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/communications/templates",
    "category": "communications",
    "summary": "Create tenant communication templates for partner workflows.",
    "required_scopes": [
      "write:communications"
    ],
    "typescript_entry_point": "client.communications.templates.create",
    "python_entry_point": "client.communications.templates.create",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/communications/messages",
    "category": "communications",
    "summary": "List tenant communication messages and recipient counts.",
    "required_scopes": [
      "read:communications",
      "write:communications"
    ],
    "typescript_entry_point": "client.communications.messages.list",
    "python_entry_point": "client.communications.messages.list",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/communications/messages",
    "category": "communications",
    "summary": "Create scoped tenant messages from partner systems.",
    "required_scopes": [
      "write:communications"
    ],
    "typescript_entry_point": "client.communications.messages.create",
    "python_entry_point": "client.communications.messages.create",
    "webhook_events": [
      "communications.message.created"
    ]
  },
  {
    "method": "GET",
    "path": "/sdk/communications/messages/{message_id}/recipients",
    "category": "communications",
    "summary": "Inspect expanded recipients for a tenant message.",
    "required_scopes": [
      "read:communications",
      "write:communications"
    ],
    "typescript_entry_point": "client.communications.messages.recipients",
    "python_entry_point": "client.communications.messages.recipients",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/communications/messages/{message_id}/dispatch",
    "category": "communications",
    "summary": "Dispatch a prepared message through configured tenant delivery adapters.",
    "required_scopes": [
      "write:communications"
    ],
    "typescript_entry_point": "client.communications.messages.dispatch",
    "python_entry_point": "client.communications.messages.dispatch",
    "webhook_events": [
      "communications.message.dispatched"
    ]
  },
  {
    "method": "GET",
    "path": "/sdk/billing/plans",
    "category": "billing",
    "summary": "List SaaS billing plans for tenant provisioning sync.",
    "required_scopes": [
      "read:billing",
      "write:billing"
    ],
    "typescript_entry_point": "client.billing.plans.list",
    "python_entry_point": "client.billing.plans.list",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/billing/subscriptions",
    "category": "billing",
    "summary": "List tenant SaaS subscriptions.",
    "required_scopes": [
      "read:billing",
      "write:billing"
    ],
    "typescript_entry_point": "client.billing.subscriptions.list",
    "python_entry_point": "client.billing.subscriptions.list",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/billing/meters",
    "category": "billing",
    "summary": "List billable usage meters.",
    "required_scopes": [
      "read:billing",
      "write:billing"
    ],
    "typescript_entry_point": "client.billing.meters.list",
    "python_entry_point": "client.billing.meters.list",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/billing/usage",
    "category": "billing",
    "summary": "List tenant usage records.",
    "required_scopes": [
      "read:billing",
      "write:billing"
    ],
    "typescript_entry_point": "client.billing.usage.list",
    "python_entry_point": "client.billing.usage.list",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/billing/usage",
    "category": "billing",
    "summary": "Record metered usage from partner systems.",
    "required_scopes": [
      "write:billing"
    ],
    "typescript_entry_point": "client.billing.usage.record",
    "python_entry_point": "client.billing.usage.record",
    "webhook_events": [
      "billing.usage.recorded"
    ]
  },
  {
    "method": "GET",
    "path": "/sdk/billing/invoices",
    "category": "billing",
    "summary": "List tenant SaaS invoices.",
    "required_scopes": [
      "read:billing",
      "write:billing"
    ],
    "typescript_entry_point": "client.billing.invoices.list",
    "python_entry_point": "client.billing.invoices.list",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/billing/entitlements",
    "category": "billing",
    "summary": "List tenant feature entitlements and current usage state.",
    "required_scopes": [
      "read:billing",
      "write:billing"
    ],
    "typescript_entry_point": "client.billing.entitlements.list",
    "python_entry_point": "client.billing.entitlements.list",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/billing/summary",
    "category": "billing",
    "summary": "Read tenant billing summary metrics.",
    "required_scopes": [
      "read:billing",
      "write:billing"
    ],
    "typescript_entry_point": "client.billing.summary.get",
    "python_entry_point": "client.billing.summary.get",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/performance/metrics",
    "category": "performance",
    "summary": "List tenant performance metric definitions.",
    "required_scopes": [
      "read:performance",
      "write:performance"
    ],
    "typescript_entry_point": "client.performance.metrics.list",
    "python_entry_point": "client.performance.metrics.list",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/performance/athletes/{athlete_profile_id}/observations",
    "category": "performance",
    "summary": "List athlete performance observations.",
    "required_scopes": [
      "read:performance",
      "write:performance"
    ],
    "typescript_entry_point": "client.performance.observations.list",
    "python_entry_point": "client.performance.observations.list",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/performance/athletes/{athlete_profile_id}/observations",
    "category": "performance",
    "summary": "Submit provider-sourced athlete performance observations.",
    "required_scopes": [
      "write:performance"
    ],
    "typescript_entry_point": "client.performance.observations.create",
    "python_entry_point": "client.performance.observations.create",
    "webhook_events": [
      "performance.observation.created"
    ]
  },
  {
    "method": "GET",
    "path": "/sdk/training/drills",
    "category": "training",
    "summary": "List tenant training drills.",
    "required_scopes": [
      "read:organization",
      "read:training"
    ],
    "typescript_entry_point": "client.training.drills.list",
    "python_entry_point": "client.training.drills.list",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/training/drills",
    "category": "training",
    "summary": "Create tenant training-library drills.",
    "required_scopes": [
      "write:training"
    ],
    "typescript_entry_point": "client.training.drills.create",
    "python_entry_point": "client.training.drills.create",
    "webhook_events": [
      "training.drill.created"
    ]
  },
  {
    "method": "GET",
    "path": "/sdk/training/plans",
    "category": "training",
    "summary": "List tenant training plans with team or athlete filtering.",
    "required_scopes": [
      "read:training",
      "write:training"
    ],
    "typescript_entry_point": "client.training.plans.list",
    "python_entry_point": "client.training.plans.list",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/training/plans",
    "category": "training",
    "summary": "Create tenant training plans from partner coaching systems.",
    "required_scopes": [
      "write:training"
    ],
    "typescript_entry_point": "client.training.plans.create",
    "python_entry_point": "client.training.plans.create",
    "webhook_events": [
      "training.plan.created"
    ]
  },
  {
    "method": "GET",
    "path": "/sdk/training/plans/{plan_id}/items",
    "category": "training",
    "summary": "List plan items for a tenant training plan.",
    "required_scopes": [
      "read:training",
      "write:training"
    ],
    "typescript_entry_point": "client.training.plans.items.list",
    "python_entry_point": "client.training.plans.items.list",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/training/plans/{plan_id}/items",
    "category": "training",
    "summary": "Add drills or custom activities to a tenant training plan.",
    "required_scopes": [
      "write:training"
    ],
    "typescript_entry_point": "client.training.plans.items.add",
    "python_entry_point": "client.training.plans.items.add",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/training/sessions",
    "category": "training",
    "summary": "List scheduled tenant training sessions.",
    "required_scopes": [
      "read:training",
      "write:training"
    ],
    "typescript_entry_point": "client.training.sessions.list",
    "python_entry_point": "client.training.sessions.list",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/training/sessions",
    "category": "training",
    "summary": "Create scheduled tenant training sessions.",
    "required_scopes": [
      "write:training"
    ],
    "typescript_entry_point": "client.training.sessions.create",
    "python_entry_point": "client.training.sessions.create",
    "webhook_events": [
      "training.session.created"
    ]
  },
  {
    "method": "GET",
    "path": "/sdk/training/sessions/{session_plan_id}/feedback",
    "category": "training",
    "summary": "List post-session athlete feedback records.",
    "required_scopes": [
      "read:training",
      "write:training"
    ],
    "typescript_entry_point": "client.training.sessions.feedback.list",
    "python_entry_point": "client.training.sessions.feedback.list",
    "webhook_events": []
  },
  {
    "method": "POST",
    "path": "/sdk/training/sessions/{session_plan_id}/feedback",
    "category": "training",
    "summary": "Record post-session feedback and readiness data.",
    "required_scopes": [
      "write:training"
    ],
    "typescript_entry_point": "client.training.sessions.feedback.record",
    "python_entry_point": "client.training.sessions.feedback.record",
    "webhook_events": [
      "training.feedback.recorded"
    ]
  },
  {
    "method": "POST",
    "path": "/sdk/training/availability",
    "category": "training",
    "summary": "Suggest schedule windows for tenant training sessions.",
    "required_scopes": [
      "read:training",
      "write:training"
    ],
    "typescript_entry_point": "client.training.availability.suggest",
    "python_entry_point": "client.training.availability.suggest",
    "webhook_events": []
  },
  {
    "method": "GET",
    "path": "/sdk/training/calendar-artifact",
    "category": "training",
    "summary": "Export checksumed iCalendar training artifacts.",
    "required_scopes": [
      "read:training",
      "write:training"
    ],
    "typescript_entry_point": "client.training.calendar.export",
    "python_entry_point": "client.training.calendar.export",
    "webhook_events": []
  }
])

__all__ = ["AFROLETE_SDK_ENDPOINTS"]
