"""add communications and notifications

Revision ID: 001fdd0cead7
Revises: 5ae823a88e0f
Create Date: 2026-05-27 06:20:01.858634
"""

from collections.abc import Sequence

import app.models.base
import sqlalchemy as sa
from alembic import op



revision: str = "001fdd0cead7"
down_revision: str | None = "5ae823a88e0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_templates',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('message_type', sa.Enum('announcement', 'alert', 'reminder', 'request', 'report', name='communicationmessagetype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'push', 'email', 'sms', 'whatsapp', 'telegram', name='communicationchannel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('subject_template', sa.String(length=240), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('variables', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_communication_templates_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_templates')),
    sa.UniqueConstraint('organization_id', 'name', 'channel', name='uq_communication_templates_org_name_channel')
    )
    op.create_index(op.f('ix_communication_templates_channel'), 'communication_templates', ['channel'], unique=False)
    op.create_index(op.f('ix_communication_templates_message_type'), 'communication_templates', ['message_type'], unique=False)
    op.create_index(op.f('ix_communication_templates_name'), 'communication_templates', ['name'], unique=False)
    op.create_index(op.f('ix_communication_templates_organization_id'), 'communication_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_communication_templates_status'), 'communication_templates', ['status'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('person_id', app.models.base.GUID(), nullable=False),
    sa.Column('frequency', sa.Enum('immediate', 'daily_digest', 'weekly_digest', name='notificationfrequency', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('channel_preference', sa.Enum('app', 'email', 'sms', 'all', name='channelpreference', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('emergency_override', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notification_preferences_organization_id_organizations')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_notification_preferences_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('organization_id', 'person_id', name='uq_notification_preferences_org_person')
    )
    op.create_index(op.f('ix_notification_preferences_channel_preference'), 'notification_preferences', ['channel_preference'], unique=False)
    op.create_index(op.f('ix_notification_preferences_frequency'), 'notification_preferences', ['frequency'], unique=False)
    op.create_index(op.f('ix_notification_preferences_organization_id'), 'notification_preferences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_person_id'), 'notification_preferences', ['person_id'], unique=False)
    op.create_table('communication_messages',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('template_id', app.models.base.GUID(), nullable=True),
    sa.Column('created_by_person_id', app.models.base.GUID(), nullable=True),
    sa.Column('message_type', sa.Enum('announcement', 'alert', 'reminder', 'request', 'report', name='communicationmessagetype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'push', 'email', 'sms', 'whatsapp', 'telegram', name='communicationchannel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('scope_type', sa.Enum('organization', 'team', 'event', 'person', name='communicationscopetype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('scope_id', app.models.base.GUID(), nullable=False),
    sa.Column('subject', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_override', sa.Boolean(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['persons.id'], name=op.f('fk_communication_messages_created_by_person_id_persons')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_communication_messages_organization_id_organizations')),
    sa.ForeignKeyConstraint(['template_id'], ['communication_templates.id'], name=op.f('fk_communication_messages_template_id_communication_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_messages'))
    )
    op.create_index(op.f('ix_communication_messages_channel'), 'communication_messages', ['channel'], unique=False)
    op.create_index(op.f('ix_communication_messages_message_type'), 'communication_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_communication_messages_organization_id'), 'communication_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_scheduled_for'), 'communication_messages', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_communication_messages_scope_id'), 'communication_messages', ['scope_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_scope_type'), 'communication_messages', ['scope_type'], unique=False)
    op.create_index(op.f('ix_communication_messages_sent_at'), 'communication_messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_communication_messages_status'), 'communication_messages', ['status'], unique=False)
    op.create_index(op.f('ix_communication_messages_template_id'), 'communication_messages', ['template_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_urgent'), 'communication_messages', ['urgent'], unique=False)
    op.create_table('message_recipients',
    sa.Column('message_id', app.models.base.GUID(), nullable=False),
    sa.Column('person_id', app.models.base.GUID(), nullable=False),
    sa.Column('destination', sa.String(length=320), nullable=True),
    sa.Column('delivery_status', sa.Enum('queued', 'sent', 'delivered', 'read', 'failed', 'suppressed', name='messagedeliverystatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['communication_messages.id'], name=op.f('fk_message_recipients_message_id_communication_messages')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_message_recipients_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_recipients')),
    sa.UniqueConstraint('message_id', 'person_id', name='uq_message_recipients_message_person')
    )
    op.create_index(op.f('ix_message_recipients_delivered_at'), 'message_recipients', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_message_recipients_delivery_status'), 'message_recipients', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_message_recipients_destination'), 'message_recipients', ['destination'], unique=False)
    op.create_index(op.f('ix_message_recipients_message_id'), 'message_recipients', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_recipients_person_id'), 'message_recipients', ['person_id'], unique=False)
    op.create_index(op.f('ix_message_recipients_read_at'), 'message_recipients', ['read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_recipients_read_at'), table_name='message_recipients')
    op.drop_index(op.f('ix_message_recipients_person_id'), table_name='message_recipients')
    op.drop_index(op.f('ix_message_recipients_message_id'), table_name='message_recipients')
    op.drop_index(op.f('ix_message_recipients_destination'), table_name='message_recipients')
    op.drop_index(op.f('ix_message_recipients_delivery_status'), table_name='message_recipients')
    op.drop_index(op.f('ix_message_recipients_delivered_at'), table_name='message_recipients')
    op.drop_table('message_recipients')
    op.drop_index(op.f('ix_communication_messages_urgent'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_template_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_status'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_sent_at'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_scope_type'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_scope_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_scheduled_for'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_organization_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_message_type'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_channel'), table_name='communication_messages')
    op.drop_table('communication_messages')
    op.drop_index(op.f('ix_notification_preferences_person_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_organization_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_frequency'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_channel_preference'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_communication_templates_status'), table_name='communication_templates')
    op.drop_index(op.f('ix_communication_templates_organization_id'), table_name='communication_templates')
    op.drop_index(op.f('ix_communication_templates_name'), table_name='communication_templates')
    op.drop_index(op.f('ix_communication_templates_message_type'), table_name='communication_templates')
    op.drop_index(op.f('ix_communication_templates_channel'), table_name='communication_templates')
    op.drop_table('communication_templates')
    # ### end Alembic commands ###
