"""add saas billing subscriptions

Revision ID: 289c8a99ccde
Revises: a1d6a3882c4e
Create Date: 2026-05-27 07:25:42.714272
"""

from collections.abc import Sequence

import app.models.base
import sqlalchemy as sa
from alembic import op


revision: str = "289c8a99ccde"
down_revision: str | None = "a1d6a3882c4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_cycle', sa.Enum('monthly', 'quarterly', 'annual', name='billingcycle', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('included_athletes', sa.Integer(), nullable=False),
    sa.Column('included_teams', sa.Integer(), nullable=False),
    sa.Column('included_agent_tasks', sa.Integer(), nullable=False),
    sa.Column('included_storage_gb', sa.Integer(), nullable=False),
    sa.Column('per_athlete_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('per_agent_task_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_billing_plans_code'))
    )
    op.create_index(op.f('ix_billing_plans_billing_cycle'), 'billing_plans', ['billing_cycle'], unique=False)
    op.create_index(op.f('ix_billing_plans_code'), 'billing_plans', ['code'], unique=False)
    op.create_index(op.f('ix_billing_plans_name'), 'billing_plans', ['name'], unique=False)
    op.create_index(op.f('ix_billing_plans_status'), 'billing_plans', ['status'], unique=False)
    op.create_table('usage_meters',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.Enum('athlete', 'team', 'agent_task', 'report', 'storage_gb', 'message', name='usageunit', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('included_quantity', sa.Integer(), nullable=False),
    sa.Column('overage_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('aggregation', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_meters')),
    sa.UniqueConstraint('code', name=op.f('uq_usage_meters_code'))
    )
    op.create_index(op.f('ix_usage_meters_code'), 'usage_meters', ['code'], unique=False)
    op.create_index(op.f('ix_usage_meters_status'), 'usage_meters', ['status'], unique=False)
    op.create_index(op.f('ix_usage_meters_unit'), 'usage_meters', ['unit'], unique=False)
    op.create_table('tenant_subscriptions',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('billing_plan_id', app.models.base.GUID(), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'paused', 'cancelled', name='subscriptionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('billing_cycle', sa.Enum('monthly', 'quarterly', 'annual', name='billingcycle', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('current_period_start', sa.Date(), nullable=False),
    sa.Column('current_period_end', sa.Date(), nullable=False),
    sa.Column('trial_ends_on', sa.Date(), nullable=True),
    sa.Column('next_billing_on', sa.Date(), nullable=True),
    sa.Column('seats_purchased', sa.Integer(), nullable=False),
    sa.Column('negotiated_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_code', sa.String(length=80), nullable=True),
    sa.Column('external_customer_id', sa.String(length=180), nullable=True),
    sa.Column('external_subscription_id', sa.String(length=180), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_plan_id'], ['billing_plans.id'], name=op.f('fk_tenant_subscriptions_billing_plan_id_billing_plans')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_tenant_subscriptions_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_subscriptions'))
    )
    op.create_index(op.f('ix_tenant_subscriptions_billing_cycle'), 'tenant_subscriptions', ['billing_cycle'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_billing_plan_id'), 'tenant_subscriptions', ['billing_plan_id'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_current_period_end'), 'tenant_subscriptions', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_current_period_start'), 'tenant_subscriptions', ['current_period_start'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_discount_code'), 'tenant_subscriptions', ['discount_code'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_external_customer_id'), 'tenant_subscriptions', ['external_customer_id'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_external_subscription_id'), 'tenant_subscriptions', ['external_subscription_id'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_next_billing_on'), 'tenant_subscriptions', ['next_billing_on'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_organization_id'), 'tenant_subscriptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_status'), 'tenant_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_trial_ends_on'), 'tenant_subscriptions', ['trial_ends_on'], unique=False)
    op.create_table('billing_entitlements',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('subscription_id', app.models.base.GUID(), nullable=False),
    sa.Column('feature_key', sa.String(length=120), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=True),
    sa.Column('used_value', sa.Integer(), nullable=False),
    sa.Column('resets_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_billing_entitlements_organization_id_organizations')),
    sa.ForeignKeyConstraint(['subscription_id'], ['tenant_subscriptions.id'], name=op.f('fk_billing_entitlements_subscription_id_tenant_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_entitlements')),
    sa.UniqueConstraint('subscription_id', 'feature_key', name=op.f('uq_billing_entitlements_subscription_id'))
    )
    op.create_index(op.f('ix_billing_entitlements_feature_key'), 'billing_entitlements', ['feature_key'], unique=False)
    op.create_index(op.f('ix_billing_entitlements_organization_id'), 'billing_entitlements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_billing_entitlements_resets_on'), 'billing_entitlements', ['resets_on'], unique=False)
    op.create_index(op.f('ix_billing_entitlements_status'), 'billing_entitlements', ['status'], unique=False)
    op.create_index(op.f('ix_billing_entitlements_subscription_id'), 'billing_entitlements', ['subscription_id'], unique=False)
    op.create_table('saas_invoices',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('subscription_id', app.models.base.GUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=80), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'paid', 'partial', 'void', 'uncollectible', name='billinginvoicestatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('line_items', sa.Text(), nullable=True),
    sa.Column('external_invoice_id', sa.String(length=180), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_saas_invoices_organization_id_organizations')),
    sa.ForeignKeyConstraint(['subscription_id'], ['tenant_subscriptions.id'], name=op.f('fk_saas_invoices_subscription_id_tenant_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saas_invoices'))
    )
    op.create_index(op.f('ix_saas_invoices_due_on'), 'saas_invoices', ['due_on'], unique=False)
    op.create_index(op.f('ix_saas_invoices_external_invoice_id'), 'saas_invoices', ['external_invoice_id'], unique=False)
    op.create_index(op.f('ix_saas_invoices_invoice_number'), 'saas_invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_saas_invoices_organization_id'), 'saas_invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_saas_invoices_period_end'), 'saas_invoices', ['period_end'], unique=False)
    op.create_index(op.f('ix_saas_invoices_period_start'), 'saas_invoices', ['period_start'], unique=False)
    op.create_index(op.f('ix_saas_invoices_status'), 'saas_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_saas_invoices_subscription_id'), 'saas_invoices', ['subscription_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('subscription_id', app.models.base.GUID(), nullable=False),
    sa.Column('usage_meter_id', app.models.base.GUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('external_reference', sa.String(length=180), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_usage_records_organization_id_organizations')),
    sa.ForeignKeyConstraint(['subscription_id'], ['tenant_subscriptions.id'], name=op.f('fk_usage_records_subscription_id_tenant_subscriptions')),
    sa.ForeignKeyConstraint(['usage_meter_id'], ['usage_meters.id'], name=op.f('fk_usage_records_usage_meter_id_usage_meters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records'))
    )
    op.create_index(op.f('ix_usage_records_external_reference'), 'usage_records', ['external_reference'], unique=False)
    op.create_index(op.f('ix_usage_records_organization_id'), 'usage_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_usage_records_recorded_at'), 'usage_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_usage_records_source'), 'usage_records', ['source'], unique=False)
    op.create_index(op.f('ix_usage_records_subscription_id'), 'usage_records', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_usage_records_usage_meter_id'), 'usage_records', ['usage_meter_id'], unique=False)
    op.create_table('saas_payments',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('invoice_id', app.models.base.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('external_payment_id', sa.String(length=180), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['saas_invoices.id'], name=op.f('fk_saas_payments_invoice_id_saas_invoices')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_saas_payments_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saas_payments'))
    )
    op.create_index(op.f('ix_saas_payments_external_payment_id'), 'saas_payments', ['external_payment_id'], unique=False)
    op.create_index(op.f('ix_saas_payments_invoice_id'), 'saas_payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_saas_payments_organization_id'), 'saas_payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_saas_payments_received_at'), 'saas_payments', ['received_at'], unique=False)
    op.create_index(op.f('ix_saas_payments_status'), 'saas_payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saas_payments_status'), table_name='saas_payments')
    op.drop_index(op.f('ix_saas_payments_received_at'), table_name='saas_payments')
    op.drop_index(op.f('ix_saas_payments_organization_id'), table_name='saas_payments')
    op.drop_index(op.f('ix_saas_payments_invoice_id'), table_name='saas_payments')
    op.drop_index(op.f('ix_saas_payments_external_payment_id'), table_name='saas_payments')
    op.drop_table('saas_payments')
    op.drop_index(op.f('ix_usage_records_usage_meter_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_subscription_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_source'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_recorded_at'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_organization_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_external_reference'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_saas_invoices_subscription_id'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_status'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_period_start'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_period_end'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_organization_id'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_invoice_number'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_external_invoice_id'), table_name='saas_invoices')
    op.drop_index(op.f('ix_saas_invoices_due_on'), table_name='saas_invoices')
    op.drop_table('saas_invoices')
    op.drop_index(op.f('ix_billing_entitlements_subscription_id'), table_name='billing_entitlements')
    op.drop_index(op.f('ix_billing_entitlements_status'), table_name='billing_entitlements')
    op.drop_index(op.f('ix_billing_entitlements_resets_on'), table_name='billing_entitlements')
    op.drop_index(op.f('ix_billing_entitlements_organization_id'), table_name='billing_entitlements')
    op.drop_index(op.f('ix_billing_entitlements_feature_key'), table_name='billing_entitlements')
    op.drop_table('billing_entitlements')
    op.drop_index(op.f('ix_tenant_subscriptions_trial_ends_on'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_status'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_organization_id'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_next_billing_on'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_external_subscription_id'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_external_customer_id'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_discount_code'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_current_period_start'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_current_period_end'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_billing_plan_id'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_billing_cycle'), table_name='tenant_subscriptions')
    op.drop_table('tenant_subscriptions')
    op.drop_index(op.f('ix_usage_meters_unit'), table_name='usage_meters')
    op.drop_index(op.f('ix_usage_meters_status'), table_name='usage_meters')
    op.drop_index(op.f('ix_usage_meters_code'), table_name='usage_meters')
    op.drop_table('usage_meters')
    op.drop_index(op.f('ix_billing_plans_status'), table_name='billing_plans')
    op.drop_index(op.f('ix_billing_plans_name'), table_name='billing_plans')
    op.drop_index(op.f('ix_billing_plans_code'), table_name='billing_plans')
    op.drop_index(op.f('ix_billing_plans_billing_cycle'), table_name='billing_plans')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###
