"""baseline schema

Revision ID: 537570abceee
Revises:
Create Date: 2026-05-27 04:08:10.733884
"""

from collections.abc import Sequence

import app.models.base
import sqlalchemy as sa
from alembic import op


revision: str = "537570abceee"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column(
            "organization_type",
            sa.Enum(
                "club",
                "school",
                "academy",
                "association",
                "federation",
                "event_operator",
                name="organizationtype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "association_level",
            sa.Enum(
                "national",
                "regional",
                "local",
                "special",
                name="associationlevel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("parent_id", app.models.base.GUID(), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("primary_sport", sa.String(length=80), nullable=True),
        sa.Column("mission", sa.Text(), nullable=True),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["organizations.id"],
            name=op.f("fk_organizations_parent_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(
        op.f("ix_organizations_association_level"),
        "organizations",
        ["association_level"],
        unique=False,
    )
    op.create_index(op.f("ix_organizations_name"), "organizations", ["name"], unique=False)
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "persons",
        sa.Column("display_name", sa.String(length=240), nullable=False),
        sa.Column("given_name", sa.String(length=120), nullable=True),
        sa.Column("family_name", sa.String(length=120), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("primary_email", sa.String(length=320), nullable=True),
        sa.Column("primary_phone", sa.String(length=64), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_persons")),
    )
    op.create_index(op.f("ix_persons_display_name"), "persons", ["display_name"], unique=False)
    op.create_index(op.f("ix_persons_primary_email"), "persons", ["primary_email"], unique=False)
    op.create_table(
        "agents",
        sa.Column("organization_id", app.models.base.GUID(), nullable=True),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "coaching",
                "operations",
                "safeguarding",
                "analytics",
                "communications",
                "scouting",
                name="agentkind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("model_policy", sa.String(length=120), nullable=True),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agents_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
    )
    op.create_index(op.f("ix_agents_kind"), "agents", ["kind"], unique=False)
    op.create_index(op.f("ix_agents_organization_id"), "agents", ["organization_id"], unique=False)
    op.create_index(op.f("ix_agents_status"), "agents", ["status"], unique=False)
    op.create_table(
        "app_users",
        sa.Column("keycloak_sub", sa.String(length=128), nullable=False),
        sa.Column("person_id", app.models.base.GUID(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=240), nullable=True),
        sa.Column("locale", sa.String(length=32), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_app_users_person_id_persons")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_users")),
    )
    op.create_index(op.f("ix_app_users_email"), "app_users", ["email"], unique=False)
    op.create_index(op.f("ix_app_users_keycloak_sub"), "app_users", ["keycloak_sub"], unique=True)
    op.create_index(op.f("ix_app_users_person_id"), "app_users", ["person_id"], unique=False)
    op.create_table(
        "athlete_profiles",
        sa.Column("organization_id", app.models.base.GUID(), nullable=False),
        sa.Column("person_id", app.models.base.GUID(), nullable=False),
        sa.Column("athlete_code", sa.String(length=80), nullable=True),
        sa.Column("dominant_side", sa.String(length=40), nullable=True),
        sa.Column("medical_visibility", sa.String(length=40), nullable=False),
        sa.Column("development_notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_athlete_profiles_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_athlete_profiles_person_id_persons")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_athlete_profiles")),
        sa.UniqueConstraint(
            "organization_id", "person_id", name=op.f("uq_athlete_profiles_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_athlete_profiles_athlete_code"), "athlete_profiles", ["athlete_code"], unique=False
    )
    op.create_index(
        op.f("ix_athlete_profiles_organization_id"),
        "athlete_profiles",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_athlete_profiles_person_id"), "athlete_profiles", ["person_id"], unique=False
    )
    op.create_table(
        "committees",
        sa.Column("organization_id", app.models.base.GUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "national",
                "regional",
                "local",
                "special",
                name="associationlevel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("mandate", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_committees_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_committees")),
        sa.UniqueConstraint("organization_id", "name", name=op.f("uq_committees_organization_id")),
    )
    op.create_index(op.f("ix_committees_level"), "committees", ["level"], unique=False)
    op.create_index(op.f("ix_committees_name"), "committees", ["name"], unique=False)
    op.create_index(
        op.f("ix_committees_organization_id"), "committees", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_committees_status"), "committees", ["status"], unique=False)
    op.create_table(
        "guardian_relationships",
        sa.Column("athlete_person_id", app.models.base.GUID(), nullable=False),
        sa.Column("guardian_person_id", app.models.base.GUID(), nullable=False),
        sa.Column("relationship", sa.String(length=80), nullable=False),
        sa.Column("can_sign_consent", sa.Boolean(), nullable=False),
        sa.Column("can_view_medical", sa.Boolean(), nullable=False),
        sa.Column("emergency_contact", sa.Boolean(), nullable=False),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["athlete_person_id"],
            ["persons.id"],
            name=op.f("fk_guardian_relationships_athlete_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["guardian_person_id"],
            ["persons.id"],
            name=op.f("fk_guardian_relationships_guardian_person_id_persons"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guardian_relationships")),
        sa.UniqueConstraint(
            "athlete_person_id",
            "guardian_person_id",
            name=op.f("uq_guardian_relationships_athlete_person_id"),
        ),
    )
    op.create_index(
        op.f("ix_guardian_relationships_athlete_person_id"),
        "guardian_relationships",
        ["athlete_person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_guardian_relationships_guardian_person_id"),
        "guardian_relationships",
        ["guardian_person_id"],
        unique=False,
    )
    op.create_table(
        "memberships",
        sa.Column("organization_id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "subject_type",
            sa.Enum(
                "person",
                "organization",
                "team",
                name="membersubjecttype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("subject_id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "coach",
                "staff",
                "athlete",
                "guardian",
                "viewer",
                "agent",
                name="membershiprole",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint(
            "organization_id",
            "subject_type",
            "subject_id",
            "role",
            name="uq_memberships_subject_role",
        ),
    )
    op.create_index(
        op.f("ix_memberships_organization_id"), "memberships", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_memberships_role"), "memberships", ["role"], unique=False)
    op.create_index(op.f("ix_memberships_status"), "memberships", ["status"], unique=False)
    op.create_index(op.f("ix_memberships_subject_id"), "memberships", ["subject_id"], unique=False)
    op.create_index(
        op.f("ix_memberships_subject_type"), "memberships", ["subject_type"], unique=False
    )
    op.create_table(
        "teams",
        sa.Column("organization_id", app.models.base.GUID(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("sport", sa.String(length=80), nullable=False),
        sa.Column(
            "sport_format",
            sa.Enum(
                "team",
                "individual",
                "mixed",
                name="sportformat",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("age_group", sa.String(length=80), nullable=True),
        sa.Column("gender_category", sa.String(length=80), nullable=True),
        sa.Column("season_label", sa.String(length=80), nullable=True),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_teams_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
    )
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=False)
    op.create_index(op.f("ix_teams_organization_id"), "teams", ["organization_id"], unique=False)
    op.create_index(op.f("ix_teams_sport"), "teams", ["sport"], unique=False)
    op.create_index(op.f("ix_teams_sport_format"), "teams", ["sport_format"], unique=False)
    op.create_table(
        "agent_assignments",
        sa.Column("agent_id", app.models.base.GUID(), nullable=False),
        sa.Column("organization_id", app.models.base.GUID(), nullable=False),
        sa.Column("scope_type", sa.String(length=80), nullable=False),
        sa.Column("scope_id", sa.String(length=120), nullable=False),
        sa.Column("granted_by_person_id", app.models.base.GUID(), nullable=True),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_agent_assignments_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_person_id"],
            ["persons.id"],
            name=op.f("fk_agent_assignments_granted_by_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_assignments_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_assignments")),
    )
    op.create_index(
        op.f("ix_agent_assignments_agent_id"), "agent_assignments", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_assignments_organization_id"),
        "agent_assignments",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "agent_tasks",
        sa.Column("agent_id", app.models.base.GUID(), nullable=False),
        sa.Column("organization_id", app.models.base.GUID(), nullable=False),
        sa.Column("task_type", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "waiting_for_review",
                "completed",
                "failed",
                "cancelled",
                name="agenttaskstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("requested_by_person_id", app.models.base.GUID(), nullable=True),
        sa.Column("input_ref", sa.String(length=500), nullable=True),
        sa.Column("output_ref", sa.String(length=500), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_agent_tasks_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_tasks_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_person_id"],
            ["persons.id"],
            name=op.f("fk_agent_tasks_requested_by_person_id_persons"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_tasks")),
    )
    op.create_index(op.f("ix_agent_tasks_agent_id"), "agent_tasks", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_agent_tasks_organization_id"), "agent_tasks", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_agent_tasks_status"), "agent_tasks", ["status"], unique=False)
    op.create_index(op.f("ix_agent_tasks_task_type"), "agent_tasks", ["task_type"], unique=False)
    op.create_table(
        "committee_memberships",
        sa.Column("committee_id", app.models.base.GUID(), nullable=False),
        sa.Column("person_id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "chair",
                "vice_chair",
                "secretary",
                "treasurer",
                "member",
                "advisor",
                "ex_officio",
                name="committeerole",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committees.id"],
            name=op.f("fk_committee_memberships_committee_id_committees"),
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_committee_memberships_person_id_persons")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_committee_memberships")),
        sa.UniqueConstraint(
            "committee_id", "person_id", "role", name="uq_committee_memberships_person_role"
        ),
    )
    op.create_index(
        op.f("ix_committee_memberships_committee_id"),
        "committee_memberships",
        ["committee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_committee_memberships_person_id"),
        "committee_memberships",
        ["person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_committee_memberships_role"), "committee_memberships", ["role"], unique=False
    )
    op.create_index(
        op.f("ix_committee_memberships_status"), "committee_memberships", ["status"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("organization_id", app.models.base.GUID(), nullable=False),
        sa.Column("team_id", app.models.base.GUID(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "training",
                "match",
                "meeting",
                "tournament",
                "assessment",
                "community",
                name="eventtype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("venue_name", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_events_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_events_team_id_teams")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(op.f("ix_events_event_type"), "events", ["event_type"], unique=False)
    op.create_index(op.f("ix_events_organization_id"), "events", ["organization_id"], unique=False)
    op.create_index(op.f("ix_events_starts_at"), "events", ["starts_at"], unique=False)
    op.create_index(op.f("ix_events_team_id"), "events", ["team_id"], unique=False)
    op.create_table(
        "team_committees",
        sa.Column("team_id", app.models.base.GUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("mandate", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_committees_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_committees")),
        sa.UniqueConstraint("team_id", "name", name=op.f("uq_team_committees_team_id")),
    )
    op.create_index(op.f("ix_team_committees_name"), "team_committees", ["name"], unique=False)
    op.create_index(op.f("ix_team_committees_status"), "team_committees", ["status"], unique=False)
    op.create_index(
        op.f("ix_team_committees_team_id"), "team_committees", ["team_id"], unique=False
    )
    op.create_table(
        "team_roster_entries",
        sa.Column("team_id", app.models.base.GUID(), nullable=False),
        sa.Column("athlete_profile_id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "player",
                "captain",
                "vice_captain",
                "coach",
                "assistant_coach",
                "manager",
                "medic",
                "analyst",
                "substitute",
                "reserve",
                "bench",
                "individual_athlete",
                name="teamrole",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("jersey_number", sa.String(length=16), nullable=True),
        sa.Column("primary_position", sa.String(length=80), nullable=True),
        sa.Column("is_captain", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "starter",
                "bench",
                "substitute",
                "reserve",
                "injured",
                "suspended",
                "inactive",
                name="rosterstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["athlete_profile_id"],
            ["athlete_profiles.id"],
            name=op.f("fk_team_roster_entries_athlete_profile_id_athlete_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_roster_entries_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_roster_entries")),
        sa.UniqueConstraint(
            "team_id", "athlete_profile_id", name=op.f("uq_team_roster_entries_team_id")
        ),
    )
    op.create_index(
        op.f("ix_team_roster_entries_athlete_profile_id"),
        "team_roster_entries",
        ["athlete_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_team_roster_entries_status"), "team_roster_entries", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_team_roster_entries_team_id"), "team_roster_entries", ["team_id"], unique=False
    )
    op.create_table(
        "attendance_records",
        sa.Column("event_id", app.models.base.GUID(), nullable=False),
        sa.Column("person_id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "invited",
                "confirmed",
                "declined",
                "present",
                "absent",
                "late",
                "excused",
                name="attendancestatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("recorded_by_person_id", app.models.base.GUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_attendance_records_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_attendance_records_person_id_persons")
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_person_id"],
            ["persons.id"],
            name=op.f("fk_attendance_records_recorded_by_person_id_persons"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_records")),
        sa.UniqueConstraint("event_id", "person_id", name=op.f("uq_attendance_records_event_id")),
    )
    op.create_index(
        op.f("ix_attendance_records_event_id"), "attendance_records", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_records_person_id"), "attendance_records", ["person_id"], unique=False
    )
    op.create_table(
        "team_committee_memberships",
        sa.Column("team_committee_id", app.models.base.GUID(), nullable=False),
        sa.Column("person_id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "chair",
                "vice_chair",
                "secretary",
                "treasurer",
                "member",
                "advisor",
                "ex_officio",
                name="committeerole",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
            name=op.f("fk_team_committee_memberships_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["team_committee_id"],
            ["team_committees.id"],
            name=op.f("fk_team_committee_memberships_team_committee_id_team_committees"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_committee_memberships")),
        sa.UniqueConstraint(
            "team_committee_id",
            "person_id",
            "role",
            name="uq_team_committee_memberships_person_role",
        ),
    )
    op.create_index(
        op.f("ix_team_committee_memberships_person_id"),
        "team_committee_memberships",
        ["person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_team_committee_memberships_role"),
        "team_committee_memberships",
        ["role"],
        unique=False,
    )
    op.create_index(
        op.f("ix_team_committee_memberships_status"),
        "team_committee_memberships",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_team_committee_memberships_team_committee_id"),
        "team_committee_memberships",
        ["team_committee_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_team_committee_memberships_team_committee_id"),
        table_name="team_committee_memberships",
    )
    op.drop_index(
        op.f("ix_team_committee_memberships_status"), table_name="team_committee_memberships"
    )
    op.drop_index(
        op.f("ix_team_committee_memberships_role"), table_name="team_committee_memberships"
    )
    op.drop_index(
        op.f("ix_team_committee_memberships_person_id"), table_name="team_committee_memberships"
    )
    op.drop_table("team_committee_memberships")
    op.drop_index(op.f("ix_attendance_records_person_id"), table_name="attendance_records")
    op.drop_index(op.f("ix_attendance_records_event_id"), table_name="attendance_records")
    op.drop_table("attendance_records")
    op.drop_index(op.f("ix_team_roster_entries_team_id"), table_name="team_roster_entries")
    op.drop_index(op.f("ix_team_roster_entries_status"), table_name="team_roster_entries")
    op.drop_index(
        op.f("ix_team_roster_entries_athlete_profile_id"), table_name="team_roster_entries"
    )
    op.drop_table("team_roster_entries")
    op.drop_index(op.f("ix_team_committees_team_id"), table_name="team_committees")
    op.drop_index(op.f("ix_team_committees_status"), table_name="team_committees")
    op.drop_index(op.f("ix_team_committees_name"), table_name="team_committees")
    op.drop_table("team_committees")
    op.drop_index(op.f("ix_events_team_id"), table_name="events")
    op.drop_index(op.f("ix_events_starts_at"), table_name="events")
    op.drop_index(op.f("ix_events_organization_id"), table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_committee_memberships_status"), table_name="committee_memberships")
    op.drop_index(op.f("ix_committee_memberships_role"), table_name="committee_memberships")
    op.drop_index(op.f("ix_committee_memberships_person_id"), table_name="committee_memberships")
    op.drop_index(op.f("ix_committee_memberships_committee_id"), table_name="committee_memberships")
    op.drop_table("committee_memberships")
    op.drop_index(op.f("ix_agent_tasks_task_type"), table_name="agent_tasks")
    op.drop_index(op.f("ix_agent_tasks_status"), table_name="agent_tasks")
    op.drop_index(op.f("ix_agent_tasks_organization_id"), table_name="agent_tasks")
    op.drop_index(op.f("ix_agent_tasks_agent_id"), table_name="agent_tasks")
    op.drop_table("agent_tasks")
    op.drop_index(op.f("ix_agent_assignments_organization_id"), table_name="agent_assignments")
    op.drop_index(op.f("ix_agent_assignments_agent_id"), table_name="agent_assignments")
    op.drop_table("agent_assignments")
    op.drop_index(op.f("ix_teams_sport_format"), table_name="teams")
    op.drop_index(op.f("ix_teams_sport"), table_name="teams")
    op.drop_index(op.f("ix_teams_organization_id"), table_name="teams")
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_memberships_subject_type"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_subject_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_status"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_role"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_organization_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(
        op.f("ix_guardian_relationships_guardian_person_id"), table_name="guardian_relationships"
    )
    op.drop_index(
        op.f("ix_guardian_relationships_athlete_person_id"), table_name="guardian_relationships"
    )
    op.drop_table("guardian_relationships")
    op.drop_index(op.f("ix_committees_status"), table_name="committees")
    op.drop_index(op.f("ix_committees_organization_id"), table_name="committees")
    op.drop_index(op.f("ix_committees_name"), table_name="committees")
    op.drop_index(op.f("ix_committees_level"), table_name="committees")
    op.drop_table("committees")
    op.drop_index(op.f("ix_athlete_profiles_person_id"), table_name="athlete_profiles")
    op.drop_index(op.f("ix_athlete_profiles_organization_id"), table_name="athlete_profiles")
    op.drop_index(op.f("ix_athlete_profiles_athlete_code"), table_name="athlete_profiles")
    op.drop_table("athlete_profiles")
    op.drop_index(op.f("ix_app_users_person_id"), table_name="app_users")
    op.drop_index(op.f("ix_app_users_keycloak_sub"), table_name="app_users")
    op.drop_index(op.f("ix_app_users_email"), table_name="app_users")
    op.drop_table("app_users")
    op.drop_index(op.f("ix_agents_status"), table_name="agents")
    op.drop_index(op.f("ix_agents_organization_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_kind"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_persons_primary_email"), table_name="persons")
    op.drop_index(op.f("ix_persons_display_name"), table_name="persons")
    op.drop_table("persons")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_association_level"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
