"""add competition management

Revision ID: 5ae823a88e0f
Revises: b23079d70437
Create Date: 2026-05-27 06:04:49.832034
"""

from collections.abc import Sequence

import app.models.base
import sqlalchemy as sa
from alembic import op



revision: str = "5ae823a88e0f"
down_revision: str | None = "b23079d70437"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('sport', sa.String(length=80), nullable=False),
    sa.Column('competition_type', sa.Enum('league', 'tournament', 'cup', 'friendly_series', name='competitiontype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('format', sa.Enum('round_robin', 'single_elimination', 'double_elimination', 'group_knockout', 'swiss', 'friendly', name='competitionformat', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('season_label', sa.String(length=80), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'active', 'completed', 'cancelled', name='competitionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('points_for_win', sa.Integer(), nullable=False),
    sa.Column('points_for_draw', sa.Integer(), nullable=False),
    sa.Column('points_for_loss', sa.Integer(), nullable=False),
    sa.Column('tiebreakers', sa.Text(), nullable=True),
    sa.Column('rules_summary', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_competitions_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitions'))
    )
    op.create_index(op.f('ix_competitions_competition_type'), 'competitions', ['competition_type'], unique=False)
    op.create_index(op.f('ix_competitions_ends_on'), 'competitions', ['ends_on'], unique=False)
    op.create_index(op.f('ix_competitions_format'), 'competitions', ['format'], unique=False)
    op.create_index(op.f('ix_competitions_name'), 'competitions', ['name'], unique=False)
    op.create_index(op.f('ix_competitions_organization_id'), 'competitions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_competitions_season_label'), 'competitions', ['season_label'], unique=False)
    op.create_index(op.f('ix_competitions_sport'), 'competitions', ['sport'], unique=False)
    op.create_index(op.f('ix_competitions_starts_on'), 'competitions', ['starts_on'], unique=False)
    op.create_index(op.f('ix_competitions_status'), 'competitions', ['status'], unique=False)
    op.create_table('competition_participants',
    sa.Column('competition_id', app.models.base.GUID(), nullable=False),
    sa.Column('team_id', app.models.base.GUID(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('group_label', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_competition_participants_competition_id_competitions')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_competition_participants_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition_participants')),
    sa.UniqueConstraint('competition_id', 'team_id', name='uq_competition_participants_competition_team')
    )
    op.create_index(op.f('ix_competition_participants_competition_id'), 'competition_participants', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_participants_group_label'), 'competition_participants', ['group_label'], unique=False)
    op.create_index(op.f('ix_competition_participants_seed'), 'competition_participants', ['seed'], unique=False)
    op.create_index(op.f('ix_competition_participants_status'), 'competition_participants', ['status'], unique=False)
    op.create_index(op.f('ix_competition_participants_team_id'), 'competition_participants', ['team_id'], unique=False)
    op.create_table('competition_fixtures',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('competition_id', app.models.base.GUID(), nullable=False),
    sa.Column('event_id', app.models.base.GUID(), nullable=True),
    sa.Column('home_team_id', app.models.base.GUID(), nullable=False),
    sa.Column('away_team_id', app.models.base.GUID(), nullable=False),
    sa.Column('round_label', sa.String(length=80), nullable=True),
    sa.Column('stage_label', sa.String(length=80), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'live', 'final', 'postponed', 'cancelled', name='fixturestatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('result_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_competition_fixtures_away_team_id_teams')),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_competition_fixtures_competition_id_competitions')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_competition_fixtures_event_id_events')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_competition_fixtures_home_team_id_teams')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_competition_fixtures_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition_fixtures'))
    )
    op.create_index(op.f('ix_competition_fixtures_away_team_id'), 'competition_fixtures', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_competition_fixtures_competition_id'), 'competition_fixtures', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_fixtures_event_id'), 'competition_fixtures', ['event_id'], unique=False)
    op.create_index(op.f('ix_competition_fixtures_home_team_id'), 'competition_fixtures', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_competition_fixtures_organization_id'), 'competition_fixtures', ['organization_id'], unique=False)
    op.create_index(op.f('ix_competition_fixtures_result_confirmed_at'), 'competition_fixtures', ['result_confirmed_at'], unique=False)
    op.create_index(op.f('ix_competition_fixtures_round_label'), 'competition_fixtures', ['round_label'], unique=False)
    op.create_index(op.f('ix_competition_fixtures_scheduled_at'), 'competition_fixtures', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_competition_fixtures_stage_label'), 'competition_fixtures', ['stage_label'], unique=False)
    op.create_index(op.f('ix_competition_fixtures_status'), 'competition_fixtures', ['status'], unique=False)
    op.create_table('fixture_match_events',
    sa.Column('fixture_id', app.models.base.GUID(), nullable=False),
    sa.Column('team_id', app.models.base.GUID(), nullable=False),
    sa.Column('athlete_profile_id', app.models.base.GUID(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('goal', 'own_goal', 'assist', 'yellow_card', 'red_card', 'substitution', 'injury', 'note', name='matcheventtype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], name=op.f('fk_fixture_match_events_athlete_profile_id_athlete_profiles')),
    sa.ForeignKeyConstraint(['fixture_id'], ['competition_fixtures.id'], name=op.f('fk_fixture_match_events_fixture_id_competition_fixtures')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_fixture_match_events_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fixture_match_events'))
    )
    op.create_index(op.f('ix_fixture_match_events_athlete_profile_id'), 'fixture_match_events', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_fixture_match_events_event_type'), 'fixture_match_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_fixture_match_events_fixture_id'), 'fixture_match_events', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_fixture_match_events_minute'), 'fixture_match_events', ['minute'], unique=False)
    op.create_index(op.f('ix_fixture_match_events_team_id'), 'fixture_match_events', ['team_id'], unique=False)
    op.create_table('fixture_official_assignments',
    sa.Column('fixture_id', app.models.base.GUID(), nullable=False),
    sa.Column('person_id', app.models.base.GUID(), nullable=False),
    sa.Column('role', sa.Enum('referee', 'assistant_referee', 'fourth_official', 'scorer', 'timekeeper', 'match_commissioner', name='officialrole', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'accepted', 'declined', 'confirmed', name='officialassignmentstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('certification_level', sa.String(length=120), nullable=True),
    sa.Column('conflict_notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['competition_fixtures.id'], name=op.f('fk_fixture_official_assignments_fixture_id_competition_fixtures')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_fixture_official_assignments_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fixture_official_assignments')),
    sa.UniqueConstraint('fixture_id', 'person_id', 'role', name='uq_fixture_official_assignments_person_role')
    )
    op.create_index(op.f('ix_fixture_official_assignments_fixture_id'), 'fixture_official_assignments', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_fixture_official_assignments_person_id'), 'fixture_official_assignments', ['person_id'], unique=False)
    op.create_index(op.f('ix_fixture_official_assignments_role'), 'fixture_official_assignments', ['role'], unique=False)
    op.create_index(op.f('ix_fixture_official_assignments_status'), 'fixture_official_assignments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixture_official_assignments_status'), table_name='fixture_official_assignments')
    op.drop_index(op.f('ix_fixture_official_assignments_role'), table_name='fixture_official_assignments')
    op.drop_index(op.f('ix_fixture_official_assignments_person_id'), table_name='fixture_official_assignments')
    op.drop_index(op.f('ix_fixture_official_assignments_fixture_id'), table_name='fixture_official_assignments')
    op.drop_table('fixture_official_assignments')
    op.drop_index(op.f('ix_fixture_match_events_team_id'), table_name='fixture_match_events')
    op.drop_index(op.f('ix_fixture_match_events_minute'), table_name='fixture_match_events')
    op.drop_index(op.f('ix_fixture_match_events_fixture_id'), table_name='fixture_match_events')
    op.drop_index(op.f('ix_fixture_match_events_event_type'), table_name='fixture_match_events')
    op.drop_index(op.f('ix_fixture_match_events_athlete_profile_id'), table_name='fixture_match_events')
    op.drop_table('fixture_match_events')
    op.drop_index(op.f('ix_competition_fixtures_status'), table_name='competition_fixtures')
    op.drop_index(op.f('ix_competition_fixtures_stage_label'), table_name='competition_fixtures')
    op.drop_index(op.f('ix_competition_fixtures_scheduled_at'), table_name='competition_fixtures')
    op.drop_index(op.f('ix_competition_fixtures_round_label'), table_name='competition_fixtures')
    op.drop_index(op.f('ix_competition_fixtures_result_confirmed_at'), table_name='competition_fixtures')
    op.drop_index(op.f('ix_competition_fixtures_organization_id'), table_name='competition_fixtures')
    op.drop_index(op.f('ix_competition_fixtures_home_team_id'), table_name='competition_fixtures')
    op.drop_index(op.f('ix_competition_fixtures_event_id'), table_name='competition_fixtures')
    op.drop_index(op.f('ix_competition_fixtures_competition_id'), table_name='competition_fixtures')
    op.drop_index(op.f('ix_competition_fixtures_away_team_id'), table_name='competition_fixtures')
    op.drop_table('competition_fixtures')
    op.drop_index(op.f('ix_competition_participants_team_id'), table_name='competition_participants')
    op.drop_index(op.f('ix_competition_participants_status'), table_name='competition_participants')
    op.drop_index(op.f('ix_competition_participants_seed'), table_name='competition_participants')
    op.drop_index(op.f('ix_competition_participants_group_label'), table_name='competition_participants')
    op.drop_index(op.f('ix_competition_participants_competition_id'), table_name='competition_participants')
    op.drop_table('competition_participants')
    op.drop_index(op.f('ix_competitions_status'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_starts_on'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_sport'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_season_label'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_organization_id'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_name'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_format'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_ends_on'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_competition_type'), table_name='competitions')
    op.drop_table('competitions')
    # ### end Alembic commands ###
