"""add safeguarding consent and organization branding

Revision ID: 6138f95a6b16
Revises: 537570abceee
Create Date: 2026-05-27 04:19:49.724367
"""

from collections.abc import Sequence

import app.models.base
import sqlalchemy as sa
from alembic import op


revision: str = "6138f95a6b16"
down_revision: str | None = "537570abceee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consent_requests",
        sa.Column("organization_id", app.models.base.GUID(), nullable=False),
        sa.Column("athlete_person_id", app.models.base.GUID(), nullable=False),
        sa.Column("guardian_person_id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "scope_type",
            sa.Enum(
                "organization",
                "team",
                "event",
                name="consentscopetype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("scope_id", app.models.base.GUID(), nullable=True),
        sa.Column(
            "channel",
            sa.Enum(
                "web_link",
                "sms",
                "whatsapp",
                "telegram",
                "email",
                "manual",
                name="consentcapturechannel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("destination", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "fulfilled",
                "expired",
                "cancelled",
                name="consentrequeststatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_message_id", sa.String(length=240), nullable=True),
        sa.Column("response_payload", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["athlete_person_id"],
            ["persons.id"],
            name=op.f("fk_consent_requests_athlete_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["guardian_person_id"],
            ["persons.id"],
            name=op.f("fk_consent_requests_guardian_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_consent_requests_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_requests")),
    )
    op.create_index(
        op.f("ix_consent_requests_athlete_person_id"),
        "consent_requests",
        ["athlete_person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_requests_channel"), "consent_requests", ["channel"], unique=False
    )
    op.create_index(
        op.f("ix_consent_requests_destination"), "consent_requests", ["destination"], unique=False
    )
    op.create_index(
        op.f("ix_consent_requests_expires_at"), "consent_requests", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_consent_requests_external_message_id"),
        "consent_requests",
        ["external_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_requests_guardian_person_id"),
        "consent_requests",
        ["guardian_person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_requests_organization_id"),
        "consent_requests",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_requests_scope_id"), "consent_requests", ["scope_id"], unique=False
    )
    op.create_index(
        op.f("ix_consent_requests_scope_type"), "consent_requests", ["scope_type"], unique=False
    )
    op.create_index(
        op.f("ix_consent_requests_status"), "consent_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_consent_requests_token_hash"), "consent_requests", ["token_hash"], unique=True
    )
    op.create_table(
        "activity_consents",
        sa.Column("organization_id", app.models.base.GUID(), nullable=False),
        sa.Column("athlete_person_id", app.models.base.GUID(), nullable=False),
        sa.Column("guardian_person_id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "scope_type",
            sa.Enum(
                "organization",
                "team",
                "event",
                name="consentscopetype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("scope_id", app.models.base.GUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "granted",
                "denied",
                "revoked",
                "expired",
                name="consentstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_request_id", app.models.base.GUID(), nullable=True),
        sa.Column(
            "capture_channel",
            sa.Enum(
                "web_link",
                "sms",
                "whatsapp",
                "telegram",
                "email",
                "manual",
                name="consentcapturechannel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_by_person_id", app.models.base.GUID(), nullable=True),
        sa.Column("consent_text", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["athlete_person_id"],
            ["persons.id"],
            name=op.f("fk_activity_consents_athlete_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["guardian_person_id"],
            ["persons.id"],
            name=op.f("fk_activity_consents_guardian_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_activity_consents_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_person_id"],
            ["persons.id"],
            name=op.f("fk_activity_consents_recorded_by_person_id_persons"),
        ),
        sa.ForeignKeyConstraint(
            ["source_request_id"],
            ["consent_requests.id"],
            name=op.f("fk_activity_consents_source_request_id_consent_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_consents")),
        sa.UniqueConstraint(
            "athlete_person_id",
            "guardian_person_id",
            "scope_type",
            "scope_id",
            name="uq_activity_consents_guardian_scope",
        ),
    )
    op.create_index(
        op.f("ix_activity_consents_athlete_person_id"),
        "activity_consents",
        ["athlete_person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_consents_capture_channel"),
        "activity_consents",
        ["capture_channel"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_consents_guardian_person_id"),
        "activity_consents",
        ["guardian_person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_consents_organization_id"),
        "activity_consents",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_consents_scope_id"), "activity_consents", ["scope_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_consents_scope_type"), "activity_consents", ["scope_type"], unique=False
    )
    op.create_index(
        op.f("ix_activity_consents_source_request_id"),
        "activity_consents",
        ["source_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_consents_status"), "activity_consents", ["status"], unique=False
    )
    with op.batch_alter_table("attendance_records") as batch_op:
        batch_op.add_column(sa.Column("guardian_consent_id", app.models.base.GUID(), nullable=True))
        batch_op.create_index(
            op.f("ix_attendance_records_guardian_consent_id"),
            ["guardian_consent_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            op.f("fk_attendance_records_guardian_consent_id_activity_consents"),
            "activity_consents",
            ["guardian_consent_id"],
            ["id"],
        )
    op.add_column(
        "guardian_relationships",
        sa.Column(
            "relationship_kind",
            sa.Enum(
                "parent",
                "legal_guardian",
                "foster_guardian",
                "caregiver",
                "emergency_contact",
                name="guardianrelationshipkind",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="parent",
            nullable=False,
        ),
    )
    op.add_column(
        "guardian_relationships",
        sa.Column("can_pick_up", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column(
        "guardian_relationships",
        sa.Column("is_primary", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column("guardian_relationships", sa.Column("notes", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_guardian_relationships_relationship_kind"),
        "guardian_relationships",
        ["relationship_kind"],
        unique=False,
    )
    op.add_column("organizations", sa.Column("public_name", sa.String(length=240), nullable=True))
    op.add_column("organizations", sa.Column("contact_email", sa.String(length=320), nullable=True))
    op.add_column("organizations", sa.Column("contact_phone", sa.String(length=64), nullable=True))
    op.add_column("organizations", sa.Column("website_url", sa.String(length=500), nullable=True))
    op.add_column("organizations", sa.Column("subdomain", sa.String(length=120), nullable=True))
    op.add_column("organizations", sa.Column("logo_url", sa.String(length=500), nullable=True))
    op.add_column(
        "organizations", sa.Column("brand_primary_color", sa.String(length=16), nullable=True)
    )
    op.add_column(
        "organizations", sa.Column("brand_secondary_color", sa.String(length=16), nullable=True)
    )
    op.create_index(op.f("ix_organizations_subdomain"), "organizations", ["subdomain"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_organizations_subdomain"), table_name="organizations")
    op.drop_column("organizations", "brand_secondary_color")
    op.drop_column("organizations", "brand_primary_color")
    op.drop_column("organizations", "logo_url")
    op.drop_column("organizations", "subdomain")
    op.drop_column("organizations", "website_url")
    op.drop_column("organizations", "contact_phone")
    op.drop_column("organizations", "contact_email")
    op.drop_column("organizations", "public_name")
    op.drop_index(
        op.f("ix_guardian_relationships_relationship_kind"), table_name="guardian_relationships"
    )
    op.drop_column("guardian_relationships", "notes")
    op.drop_column("guardian_relationships", "is_primary")
    op.drop_column("guardian_relationships", "can_pick_up")
    op.drop_column("guardian_relationships", "relationship_kind")
    with op.batch_alter_table("attendance_records") as batch_op:
        batch_op.drop_constraint(
            op.f("fk_attendance_records_guardian_consent_id_activity_consents"),
            type_="foreignkey",
        )
        batch_op.drop_index(op.f("ix_attendance_records_guardian_consent_id"))
        batch_op.drop_column("guardian_consent_id")
    op.drop_index(op.f("ix_activity_consents_status"), table_name="activity_consents")
    op.drop_index(op.f("ix_activity_consents_source_request_id"), table_name="activity_consents")
    op.drop_index(op.f("ix_activity_consents_scope_type"), table_name="activity_consents")
    op.drop_index(op.f("ix_activity_consents_scope_id"), table_name="activity_consents")
    op.drop_index(op.f("ix_activity_consents_organization_id"), table_name="activity_consents")
    op.drop_index(op.f("ix_activity_consents_guardian_person_id"), table_name="activity_consents")
    op.drop_index(op.f("ix_activity_consents_capture_channel"), table_name="activity_consents")
    op.drop_index(op.f("ix_activity_consents_athlete_person_id"), table_name="activity_consents")
    op.drop_table("activity_consents")
    op.drop_index(op.f("ix_consent_requests_token_hash"), table_name="consent_requests")
    op.drop_index(op.f("ix_consent_requests_status"), table_name="consent_requests")
    op.drop_index(op.f("ix_consent_requests_scope_type"), table_name="consent_requests")
    op.drop_index(op.f("ix_consent_requests_scope_id"), table_name="consent_requests")
    op.drop_index(op.f("ix_consent_requests_organization_id"), table_name="consent_requests")
    op.drop_index(op.f("ix_consent_requests_guardian_person_id"), table_name="consent_requests")
    op.drop_index(op.f("ix_consent_requests_external_message_id"), table_name="consent_requests")
    op.drop_index(op.f("ix_consent_requests_expires_at"), table_name="consent_requests")
    op.drop_index(op.f("ix_consent_requests_destination"), table_name="consent_requests")
    op.drop_index(op.f("ix_consent_requests_channel"), table_name="consent_requests")
    op.drop_index(op.f("ix_consent_requests_athlete_person_id"), table_name="consent_requests")
    op.drop_table("consent_requests")
    # ### end Alembic commands ###
