"""add commercial operations

Revision ID: 68524e686723
Revises: 95a6c87596d8
Create Date: 2026-05-27 07:04:10.546330
"""

from collections.abc import Sequence

import app.models.base
import sqlalchemy as sa
from alembic import op


revision: str = "68524e686723"
down_revision: str | None = "95a6c87596d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsors',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('contact_name', sa.String(length=180), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('brand_assets_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sponsors_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sponsors')),
    sa.UniqueConstraint('organization_id', 'name', name=op.f('uq_sponsors_organization_id'))
    )
    op.create_index(op.f('ix_sponsors_contact_email'), 'sponsors', ['contact_email'], unique=False)
    op.create_index(op.f('ix_sponsors_industry'), 'sponsors', ['industry'], unique=False)
    op.create_index(op.f('ix_sponsors_name'), 'sponsors', ['name'], unique=False)
    op.create_index(op.f('ix_sponsors_organization_id'), 'sponsors', ['organization_id'], unique=False)
    op.create_table('finance_invoices',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('person_id', app.models.base.GUID(), nullable=True),
    sa.Column('team_id', app.models.base.GUID(), nullable=True),
    sa.Column('sponsor_id', app.models.base.GUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'pledged', 'paid', 'partial', 'overdue', 'completed', 'cancelled', name='commercialstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_finance_invoices_organization_id_organizations')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_finance_invoices_person_id_persons')),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], name=op.f('fk_finance_invoices_sponsor_id_sponsors')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_finance_invoices_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_invoices'))
    )
    op.create_index(op.f('ix_finance_invoices_due_on'), 'finance_invoices', ['due_on'], unique=False)
    op.create_index(op.f('ix_finance_invoices_invoice_number'), 'finance_invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_finance_invoices_organization_id'), 'finance_invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_finance_invoices_person_id'), 'finance_invoices', ['person_id'], unique=False)
    op.create_index(op.f('ix_finance_invoices_sponsor_id'), 'finance_invoices', ['sponsor_id'], unique=False)
    op.create_index(op.f('ix_finance_invoices_status'), 'finance_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_finance_invoices_team_id'), 'finance_invoices', ['team_id'], unique=False)
    op.create_table('fundraising_campaigns',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('team_id', app.models.base.GUID(), nullable=True),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('purpose', sa.String(length=240), nullable=False),
    sa.Column('goal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('raised_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('public_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'pledged', 'paid', 'partial', 'overdue', 'completed', 'cancelled', name='commercialstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_fundraising_campaigns_organization_id_organizations')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_fundraising_campaigns_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundraising_campaigns'))
    )
    op.create_index(op.f('ix_fundraising_campaigns_ends_on'), 'fundraising_campaigns', ['ends_on'], unique=False)
    op.create_index(op.f('ix_fundraising_campaigns_name'), 'fundraising_campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_fundraising_campaigns_organization_id'), 'fundraising_campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fundraising_campaigns_starts_on'), 'fundraising_campaigns', ['starts_on'], unique=False)
    op.create_index(op.f('ix_fundraising_campaigns_status'), 'fundraising_campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_fundraising_campaigns_team_id'), 'fundraising_campaigns', ['team_id'], unique=False)
    op.create_table('donations',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('campaign_id', app.models.base.GUID(), nullable=False),
    sa.Column('donor_name', sa.String(length=180), nullable=False),
    sa.Column('donor_email', sa.String(length=320), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('external_reference', sa.String(length=240), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'pledged', 'paid', 'partial', 'overdue', 'completed', 'cancelled', name='commercialstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['fundraising_campaigns.id'], name=op.f('fk_donations_campaign_id_fundraising_campaigns')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_donations_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donations'))
    )
    op.create_index(op.f('ix_donations_campaign_id'), 'donations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_donations_donor_email'), 'donations', ['donor_email'], unique=False)
    op.create_index(op.f('ix_donations_donor_name'), 'donations', ['donor_name'], unique=False)
    op.create_index(op.f('ix_donations_external_reference'), 'donations', ['external_reference'], unique=False)
    op.create_index(op.f('ix_donations_organization_id'), 'donations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_donations_status'), 'donations', ['status'], unique=False)
    op.create_table('finance_payments',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('invoice_id', app.models.base.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('external_reference', sa.String(length=240), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['finance_invoices.id'], name=op.f('fk_finance_payments_invoice_id_finance_invoices')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_finance_payments_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_payments'))
    )
    op.create_index(op.f('ix_finance_payments_external_reference'), 'finance_payments', ['external_reference'], unique=False)
    op.create_index(op.f('ix_finance_payments_invoice_id'), 'finance_payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_finance_payments_organization_id'), 'finance_payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_finance_payments_received_at'), 'finance_payments', ['received_at'], unique=False)
    op.create_table('sponsorship_agreements',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('sponsor_id', app.models.base.GUID(), nullable=False),
    sa.Column('event_id', app.models.base.GUID(), nullable=True),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('tier', sa.String(length=80), nullable=False),
    sa.Column('value_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('deliverables', sa.Text(), nullable=True),
    sa.Column('activation_notes', sa.Text(), nullable=True),
    sa.Column('roi_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'pledged', 'paid', 'partial', 'overdue', 'completed', 'cancelled', name='commercialstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_sponsorship_agreements_event_id_events')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sponsorship_agreements_organization_id_organizations')),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], name=op.f('fk_sponsorship_agreements_sponsor_id_sponsors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sponsorship_agreements'))
    )
    op.create_index(op.f('ix_sponsorship_agreements_ends_on'), 'sponsorship_agreements', ['ends_on'], unique=False)
    op.create_index(op.f('ix_sponsorship_agreements_event_id'), 'sponsorship_agreements', ['event_id'], unique=False)
    op.create_index(op.f('ix_sponsorship_agreements_name'), 'sponsorship_agreements', ['name'], unique=False)
    op.create_index(op.f('ix_sponsorship_agreements_organization_id'), 'sponsorship_agreements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sponsorship_agreements_sponsor_id'), 'sponsorship_agreements', ['sponsor_id'], unique=False)
    op.create_index(op.f('ix_sponsorship_agreements_starts_on'), 'sponsorship_agreements', ['starts_on'], unique=False)
    op.create_index(op.f('ix_sponsorship_agreements_status'), 'sponsorship_agreements', ['status'], unique=False)
    op.create_index(op.f('ix_sponsorship_agreements_tier'), 'sponsorship_agreements', ['tier'], unique=False)
    op.create_table('ticket_products',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('event_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column('access_zone', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'pledged', 'paid', 'partial', 'overdue', 'completed', 'cancelled', name='commercialstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ticket_products_event_id_events')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ticket_products_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_products'))
    )
    op.create_index(op.f('ix_ticket_products_event_id'), 'ticket_products', ['event_id'], unique=False)
    op.create_index(op.f('ix_ticket_products_name'), 'ticket_products', ['name'], unique=False)
    op.create_index(op.f('ix_ticket_products_organization_id'), 'ticket_products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ticket_products_status'), 'ticket_products', ['status'], unique=False)
    op.create_table('ticket_orders',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('ticket_product_id', app.models.base.GUID(), nullable=False),
    sa.Column('buyer_name', sa.String(length=180), nullable=False),
    sa.Column('buyer_email', sa.String(length=320), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('external_payment_reference', sa.String(length=240), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'pledged', 'paid', 'partial', 'overdue', 'completed', 'cancelled', name='commercialstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ticket_orders_organization_id_organizations')),
    sa.ForeignKeyConstraint(['ticket_product_id'], ['ticket_products.id'], name=op.f('fk_ticket_orders_ticket_product_id_ticket_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_orders'))
    )
    op.create_index(op.f('ix_ticket_orders_buyer_email'), 'ticket_orders', ['buyer_email'], unique=False)
    op.create_index(op.f('ix_ticket_orders_external_payment_reference'), 'ticket_orders', ['external_payment_reference'], unique=False)
    op.create_index(op.f('ix_ticket_orders_organization_id'), 'ticket_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ticket_orders_status'), 'ticket_orders', ['status'], unique=False)
    op.create_index(op.f('ix_ticket_orders_ticket_product_id'), 'ticket_orders', ['ticket_product_id'], unique=False)
    op.create_table('tickets',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('ticket_order_id', app.models.base.GUID(), nullable=False),
    sa.Column('ticket_product_id', app.models.base.GUID(), nullable=False),
    sa.Column('holder_name', sa.String(length=180), nullable=True),
    sa.Column('qr_token', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('issued', 'checked_in', 'void', 'refunded', name='ticketstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gate', sa.String(length=80), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_tickets_organization_id_organizations')),
    sa.ForeignKeyConstraint(['ticket_order_id'], ['ticket_orders.id'], name=op.f('fk_tickets_ticket_order_id_ticket_orders')),
    sa.ForeignKeyConstraint(['ticket_product_id'], ['ticket_products.id'], name=op.f('fk_tickets_ticket_product_id_ticket_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_index(op.f('ix_tickets_checked_in_at'), 'tickets', ['checked_in_at'], unique=False)
    op.create_index(op.f('ix_tickets_organization_id'), 'tickets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tickets_qr_token'), 'tickets', ['qr_token'], unique=True)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_order_id'), 'tickets', ['ticket_order_id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_product_id'), 'tickets', ['ticket_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_ticket_product_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticket_order_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_qr_token'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_organization_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_checked_in_at'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_ticket_orders_ticket_product_id'), table_name='ticket_orders')
    op.drop_index(op.f('ix_ticket_orders_status'), table_name='ticket_orders')
    op.drop_index(op.f('ix_ticket_orders_organization_id'), table_name='ticket_orders')
    op.drop_index(op.f('ix_ticket_orders_external_payment_reference'), table_name='ticket_orders')
    op.drop_index(op.f('ix_ticket_orders_buyer_email'), table_name='ticket_orders')
    op.drop_table('ticket_orders')
    op.drop_index(op.f('ix_ticket_products_status'), table_name='ticket_products')
    op.drop_index(op.f('ix_ticket_products_organization_id'), table_name='ticket_products')
    op.drop_index(op.f('ix_ticket_products_name'), table_name='ticket_products')
    op.drop_index(op.f('ix_ticket_products_event_id'), table_name='ticket_products')
    op.drop_table('ticket_products')
    op.drop_index(op.f('ix_sponsorship_agreements_tier'), table_name='sponsorship_agreements')
    op.drop_index(op.f('ix_sponsorship_agreements_status'), table_name='sponsorship_agreements')
    op.drop_index(op.f('ix_sponsorship_agreements_starts_on'), table_name='sponsorship_agreements')
    op.drop_index(op.f('ix_sponsorship_agreements_sponsor_id'), table_name='sponsorship_agreements')
    op.drop_index(op.f('ix_sponsorship_agreements_organization_id'), table_name='sponsorship_agreements')
    op.drop_index(op.f('ix_sponsorship_agreements_name'), table_name='sponsorship_agreements')
    op.drop_index(op.f('ix_sponsorship_agreements_event_id'), table_name='sponsorship_agreements')
    op.drop_index(op.f('ix_sponsorship_agreements_ends_on'), table_name='sponsorship_agreements')
    op.drop_table('sponsorship_agreements')
    op.drop_index(op.f('ix_finance_payments_received_at'), table_name='finance_payments')
    op.drop_index(op.f('ix_finance_payments_organization_id'), table_name='finance_payments')
    op.drop_index(op.f('ix_finance_payments_invoice_id'), table_name='finance_payments')
    op.drop_index(op.f('ix_finance_payments_external_reference'), table_name='finance_payments')
    op.drop_table('finance_payments')
    op.drop_index(op.f('ix_donations_status'), table_name='donations')
    op.drop_index(op.f('ix_donations_organization_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_external_reference'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_name'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_email'), table_name='donations')
    op.drop_index(op.f('ix_donations_campaign_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_fundraising_campaigns_team_id'), table_name='fundraising_campaigns')
    op.drop_index(op.f('ix_fundraising_campaigns_status'), table_name='fundraising_campaigns')
    op.drop_index(op.f('ix_fundraising_campaigns_starts_on'), table_name='fundraising_campaigns')
    op.drop_index(op.f('ix_fundraising_campaigns_organization_id'), table_name='fundraising_campaigns')
    op.drop_index(op.f('ix_fundraising_campaigns_name'), table_name='fundraising_campaigns')
    op.drop_index(op.f('ix_fundraising_campaigns_ends_on'), table_name='fundraising_campaigns')
    op.drop_table('fundraising_campaigns')
    op.drop_index(op.f('ix_finance_invoices_team_id'), table_name='finance_invoices')
    op.drop_index(op.f('ix_finance_invoices_status'), table_name='finance_invoices')
    op.drop_index(op.f('ix_finance_invoices_sponsor_id'), table_name='finance_invoices')
    op.drop_index(op.f('ix_finance_invoices_person_id'), table_name='finance_invoices')
    op.drop_index(op.f('ix_finance_invoices_organization_id'), table_name='finance_invoices')
    op.drop_index(op.f('ix_finance_invoices_invoice_number'), table_name='finance_invoices')
    op.drop_index(op.f('ix_finance_invoices_due_on'), table_name='finance_invoices')
    op.drop_table('finance_invoices')
    op.drop_index(op.f('ix_sponsors_organization_id'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_name'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_industry'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_contact_email'), table_name='sponsors')
    op.drop_table('sponsors')
    # ### end Alembic commands ###
