"""add asset and facility operations

Revision ID: 95a6c87596d8
Revises: 001fdd0cead7
Create Date: 2026-05-27 06:47:22.743985
"""

from collections.abc import Sequence

import app.models.base
import sqlalchemy as sa
from alembic import op


revision: str = "95a6c87596d8"
down_revision: str | None = "001fdd0cead7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('facility_type', sa.Enum('field', 'court', 'stadium', 'gym', 'pool', 'clubhouse', 'storage', 'other', name='facilitytype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('available', 'booked', 'maintenance', 'closed', 'retired', name='facilitystatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('sport', sa.String(length=80), nullable=True),
    sa.Column('surface', sa.String(length=120), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=240), nullable=True),
    sa.Column('dimensions', sa.String(length=120), nullable=True),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('maintenance_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('condition', sa.Enum('new', 'good', 'fair', 'poor', 'unusable', name='assetcondition', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('insurance_policy_ref', sa.String(length=180), nullable=True),
    sa.Column('last_inspection_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_facilities_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities'))
    )
    op.create_index(op.f('ix_facilities_condition'), 'facilities', ['condition'], unique=False)
    op.create_index(op.f('ix_facilities_facility_type'), 'facilities', ['facility_type'], unique=False)
    op.create_index(op.f('ix_facilities_last_inspection_on'), 'facilities', ['last_inspection_on'], unique=False)
    op.create_index(op.f('ix_facilities_name'), 'facilities', ['name'], unique=False)
    op.create_index(op.f('ix_facilities_organization_id'), 'facilities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_facilities_sport'), 'facilities', ['sport'], unique=False)
    op.create_index(op.f('ix_facilities_status'), 'facilities', ['status'], unique=False)
    op.create_table('equipment_items',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('facility_id', app.models.base.GUID(), nullable=True),
    sa.Column('team_id', app.models.base.GUID(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('tag_code', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=160), nullable=True),
    sa.Column('quantity_total', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('new', 'good', 'fair', 'poor', 'unusable', name='assetcondition', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('available', 'checked_out', 'maintenance', 'lost', 'retired', name='equipmentstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('storage_location', sa.String(length=240), nullable=True),
    sa.Column('min_stock_level', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('unit_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('depreciation_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('warranty_expires_on', sa.Date(), nullable=True),
    sa.Column('last_audit_on', sa.Date(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_equipment_items_facility_id_facilities')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_equipment_items_organization_id_organizations')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_equipment_items_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_items'))
    )
    op.create_index(op.f('ix_equipment_items_category'), 'equipment_items', ['category'], unique=False)
    op.create_index(op.f('ix_equipment_items_condition'), 'equipment_items', ['condition'], unique=False)
    op.create_index(op.f('ix_equipment_items_facility_id'), 'equipment_items', ['facility_id'], unique=False)
    op.create_index(op.f('ix_equipment_items_last_audit_on'), 'equipment_items', ['last_audit_on'], unique=False)
    op.create_index(op.f('ix_equipment_items_name'), 'equipment_items', ['name'], unique=False)
    op.create_index(op.f('ix_equipment_items_organization_id'), 'equipment_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_equipment_items_serial_number'), 'equipment_items', ['serial_number'], unique=False)
    op.create_index(op.f('ix_equipment_items_status'), 'equipment_items', ['status'], unique=False)
    op.create_index(op.f('ix_equipment_items_tag_code'), 'equipment_items', ['tag_code'], unique=False)
    op.create_index(op.f('ix_equipment_items_team_id'), 'equipment_items', ['team_id'], unique=False)
    op.create_index(op.f('ix_equipment_items_warranty_expires_on'), 'equipment_items', ['warranty_expires_on'], unique=False)
    op.create_table('equipment_checkouts',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('equipment_item_id', app.models.base.GUID(), nullable=False),
    sa.Column('team_id', app.models.base.GUID(), nullable=True),
    sa.Column('event_id', app.models.base.GUID(), nullable=True),
    sa.Column('borrower_person_id', app.models.base.GUID(), nullable=True),
    sa.Column('checked_out_by_person_id', app.models.base.GUID(), nullable=True),
    sa.Column('returned_by_person_id', app.models.base.GUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=240), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('checked_out', 'returned', 'overdue', 'lost', 'damaged', name='checkoutstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('condition_out', sa.String(length=40), nullable=False),
    sa.Column('condition_in', sa.String(length=40), nullable=True),
    sa.Column('condition_notes', sa.Text(), nullable=True),
    sa.Column('damage_report', sa.Text(), nullable=True),
    sa.Column('late_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_person_id'], ['persons.id'], name=op.f('fk_equipment_checkouts_borrower_person_id_persons')),
    sa.ForeignKeyConstraint(['checked_out_by_person_id'], ['persons.id'], name=op.f('fk_equipment_checkouts_checked_out_by_person_id_persons')),
    sa.ForeignKeyConstraint(['equipment_item_id'], ['equipment_items.id'], name=op.f('fk_equipment_checkouts_equipment_item_id_equipment_items')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_equipment_checkouts_event_id_events')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_equipment_checkouts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['returned_by_person_id'], ['persons.id'], name=op.f('fk_equipment_checkouts_returned_by_person_id_persons')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_equipment_checkouts_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_checkouts'))
    )
    op.create_index(op.f('ix_equipment_checkouts_borrower_person_id'), 'equipment_checkouts', ['borrower_person_id'], unique=False)
    op.create_index(op.f('ix_equipment_checkouts_checked_out_at'), 'equipment_checkouts', ['checked_out_at'], unique=False)
    op.create_index(op.f('ix_equipment_checkouts_due_at'), 'equipment_checkouts', ['due_at'], unique=False)
    op.create_index(op.f('ix_equipment_checkouts_equipment_item_id'), 'equipment_checkouts', ['equipment_item_id'], unique=False)
    op.create_index(op.f('ix_equipment_checkouts_event_id'), 'equipment_checkouts', ['event_id'], unique=False)
    op.create_index(op.f('ix_equipment_checkouts_organization_id'), 'equipment_checkouts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_equipment_checkouts_returned_at'), 'equipment_checkouts', ['returned_at'], unique=False)
    op.create_index(op.f('ix_equipment_checkouts_status'), 'equipment_checkouts', ['status'], unique=False)
    op.create_index(op.f('ix_equipment_checkouts_team_id'), 'equipment_checkouts', ['team_id'], unique=False)
    op.create_table('facility_bookings',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('facility_id', app.models.base.GUID(), nullable=False),
    sa.Column('team_id', app.models.base.GUID(), nullable=True),
    sa.Column('event_id', app.models.base.GUID(), nullable=True),
    sa.Column('requested_by_person_id', app.models.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('requested', 'approved', 'confirmed', 'checked_in', 'completed', 'cancelled', name='facilitybookingstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('requester_name', sa.String(length=180), nullable=True),
    sa.Column('requester_email', sa.String(length=255), nullable=True),
    sa.Column('expected_attendees', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deposit_required', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('insurance_certificate_ref', sa.String(length=240), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('access_code', sa.String(length=80), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_facility_bookings_event_id_events')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_facility_bookings_facility_id_facilities')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_facility_bookings_organization_id_organizations')),
    sa.ForeignKeyConstraint(['requested_by_person_id'], ['persons.id'], name=op.f('fk_facility_bookings_requested_by_person_id_persons')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_facility_bookings_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_bookings'))
    )
    op.create_index(op.f('ix_facility_bookings_ends_at'), 'facility_bookings', ['ends_at'], unique=False)
    op.create_index(op.f('ix_facility_bookings_event_id'), 'facility_bookings', ['event_id'], unique=False)
    op.create_index(op.f('ix_facility_bookings_facility_id'), 'facility_bookings', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_bookings_organization_id'), 'facility_bookings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_facility_bookings_requested_by_person_id'), 'facility_bookings', ['requested_by_person_id'], unique=False)
    op.create_index(op.f('ix_facility_bookings_starts_at'), 'facility_bookings', ['starts_at'], unique=False)
    op.create_index(op.f('ix_facility_bookings_status'), 'facility_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_facility_bookings_team_id'), 'facility_bookings', ['team_id'], unique=False)
    op.create_index(op.f('ix_facility_bookings_title'), 'facility_bookings', ['title'], unique=False)
    op.create_table('maintenance_work_orders',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('facility_id', app.models.base.GUID(), nullable=True),
    sa.Column('equipment_item_id', app.models.base.GUID(), nullable=True),
    sa.Column('assigned_to_person_id', app.models.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='workorderpriority', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'assigned', 'in_progress', 'completed', 'cancelled', name='workorderstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vendor', sa.String(length=180), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('safety_related', sa.Boolean(), nullable=False),
    sa.Column('compliance_reference', sa.String(length=240), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_person_id'], ['persons.id'], name=op.f('fk_maintenance_work_orders_assigned_to_person_id_persons')),
    sa.ForeignKeyConstraint(['equipment_item_id'], ['equipment_items.id'], name=op.f('fk_maintenance_work_orders_equipment_item_id_equipment_items')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_maintenance_work_orders_facility_id_facilities')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_maintenance_work_orders_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_work_orders'))
    )
    op.create_index(op.f('ix_maintenance_work_orders_assigned_to_person_id'), 'maintenance_work_orders', ['assigned_to_person_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_completed_at'), 'maintenance_work_orders', ['completed_at'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_due_at'), 'maintenance_work_orders', ['due_at'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_equipment_item_id'), 'maintenance_work_orders', ['equipment_item_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_facility_id'), 'maintenance_work_orders', ['facility_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_organization_id'), 'maintenance_work_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_priority'), 'maintenance_work_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_status'), 'maintenance_work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_title'), 'maintenance_work_orders', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_work_orders_title'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_status'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_priority'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_organization_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_facility_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_equipment_item_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_due_at'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_completed_at'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_assigned_to_person_id'), table_name='maintenance_work_orders')
    op.drop_table('maintenance_work_orders')
    op.drop_index(op.f('ix_facility_bookings_title'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_team_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_status'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_starts_at'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_requested_by_person_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_organization_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_facility_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_event_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_ends_at'), table_name='facility_bookings')
    op.drop_table('facility_bookings')
    op.drop_index(op.f('ix_equipment_checkouts_team_id'), table_name='equipment_checkouts')
    op.drop_index(op.f('ix_equipment_checkouts_status'), table_name='equipment_checkouts')
    op.drop_index(op.f('ix_equipment_checkouts_returned_at'), table_name='equipment_checkouts')
    op.drop_index(op.f('ix_equipment_checkouts_organization_id'), table_name='equipment_checkouts')
    op.drop_index(op.f('ix_equipment_checkouts_event_id'), table_name='equipment_checkouts')
    op.drop_index(op.f('ix_equipment_checkouts_equipment_item_id'), table_name='equipment_checkouts')
    op.drop_index(op.f('ix_equipment_checkouts_due_at'), table_name='equipment_checkouts')
    op.drop_index(op.f('ix_equipment_checkouts_checked_out_at'), table_name='equipment_checkouts')
    op.drop_index(op.f('ix_equipment_checkouts_borrower_person_id'), table_name='equipment_checkouts')
    op.drop_table('equipment_checkouts')
    op.drop_index(op.f('ix_equipment_items_warranty_expires_on'), table_name='equipment_items')
    op.drop_index(op.f('ix_equipment_items_team_id'), table_name='equipment_items')
    op.drop_index(op.f('ix_equipment_items_tag_code'), table_name='equipment_items')
    op.drop_index(op.f('ix_equipment_items_status'), table_name='equipment_items')
    op.drop_index(op.f('ix_equipment_items_serial_number'), table_name='equipment_items')
    op.drop_index(op.f('ix_equipment_items_organization_id'), table_name='equipment_items')
    op.drop_index(op.f('ix_equipment_items_name'), table_name='equipment_items')
    op.drop_index(op.f('ix_equipment_items_last_audit_on'), table_name='equipment_items')
    op.drop_index(op.f('ix_equipment_items_facility_id'), table_name='equipment_items')
    op.drop_index(op.f('ix_equipment_items_condition'), table_name='equipment_items')
    op.drop_index(op.f('ix_equipment_items_category'), table_name='equipment_items')
    op.drop_table('equipment_items')
    op.drop_index(op.f('ix_facilities_status'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_sport'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_organization_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_name'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_last_inspection_on'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_type'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_condition'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
