"""add reporting and intelligence

Revision ID: a1d6a3882c4e
Revises: 68524e686723
Create Date: 2026-05-27 07:15:20.663778
"""

from collections.abc import Sequence

import app.models.base
import sqlalchemy as sa
from alembic import op


revision: str = "a1d6a3882c4e"
down_revision: str | None = "68524e686723"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_definitions',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('category', sa.Enum('performance', 'administrative', 'operational', 'financial', 'compliance', 'intelligence', name='reportcategory', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_format', sa.Enum('online', 'pdf', 'excel', 'csv', 'api', name='reportformat', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('parameter_schema', sa.Text(), nullable=True),
    sa.Column('template', sa.Text(), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_report_definitions_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_definitions')),
    sa.UniqueConstraint('organization_id', 'name', name=op.f('uq_report_definitions_organization_id'))
    )
    op.create_index(op.f('ix_report_definitions_category'), 'report_definitions', ['category'], unique=False)
    op.create_index(op.f('ix_report_definitions_default_format'), 'report_definitions', ['default_format'], unique=False)
    op.create_index(op.f('ix_report_definitions_name'), 'report_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_report_definitions_organization_id'), 'report_definitions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_report_definitions_status'), 'report_definitions', ['status'], unique=False)
    op.create_table('predictive_risk_scores',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('athlete_profile_id', app.models.base.GUID(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_band', sa.String(length=40), nullable=False),
    sa.Column('drivers', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('valid_for_date', sa.Date(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], name=op.f('fk_predictive_risk_scores_athlete_profile_id_athlete_profiles')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_predictive_risk_scores_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictive_risk_scores'))
    )
    op.create_index(op.f('ix_predictive_risk_scores_athlete_profile_id'), 'predictive_risk_scores', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_predictive_risk_scores_model_name'), 'predictive_risk_scores', ['model_name'], unique=False)
    op.create_index(op.f('ix_predictive_risk_scores_organization_id'), 'predictive_risk_scores', ['organization_id'], unique=False)
    op.create_index(op.f('ix_predictive_risk_scores_risk_band'), 'predictive_risk_scores', ['risk_band'], unique=False)
    op.create_index(op.f('ix_predictive_risk_scores_score'), 'predictive_risk_scores', ['score'], unique=False)
    op.create_index(op.f('ix_predictive_risk_scores_valid_for_date'), 'predictive_risk_scores', ['valid_for_date'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('report_definition_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('frequency', sa.Enum('on_demand', 'daily', 'weekly', 'monthly', 'quarterly', 'on_trigger', name='reportfrequency', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('delivery_channels', sa.String(length=240), nullable=False),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scheduled_reports_organization_id_organizations')),
    sa.ForeignKeyConstraint(['report_definition_id'], ['report_definitions.id'], name=op.f('fk_scheduled_reports_report_definition_id_report_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_reports'))
    )
    op.create_index(op.f('ix_scheduled_reports_frequency'), 'scheduled_reports', ['frequency'], unique=False)
    op.create_index(op.f('ix_scheduled_reports_last_run_at'), 'scheduled_reports', ['last_run_at'], unique=False)
    op.create_index(op.f('ix_scheduled_reports_name'), 'scheduled_reports', ['name'], unique=False)
    op.create_index(op.f('ix_scheduled_reports_next_run_at'), 'scheduled_reports', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_scheduled_reports_organization_id'), 'scheduled_reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scheduled_reports_report_definition_id'), 'scheduled_reports', ['report_definition_id'], unique=False)
    op.create_index(op.f('ix_scheduled_reports_status'), 'scheduled_reports', ['status'], unique=False)
    op.create_table('generated_reports',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('report_definition_id', app.models.base.GUID(), nullable=False),
    sa.Column('requested_by_person_id', app.models.base.GUID(), nullable=True),
    sa.Column('team_id', app.models.base.GUID(), nullable=True),
    sa.Column('athlete_profile_id', app.models.base.GUID(), nullable=True),
    sa.Column('competition_id', app.models.base.GUID(), nullable=True),
    sa.Column('event_id', app.models.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('output_format', sa.Enum('online', 'pdf', 'excel', 'csv', 'api', name='reportformat', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'ready', 'failed', name='reportrunstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('artifact_url', sa.String(length=500), nullable=True),
    sa.Column('shared_token', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], name=op.f('fk_generated_reports_athlete_profile_id_athlete_profiles')),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_generated_reports_competition_id_competitions')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_generated_reports_event_id_events')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_generated_reports_organization_id_organizations')),
    sa.ForeignKeyConstraint(['report_definition_id'], ['report_definitions.id'], name=op.f('fk_generated_reports_report_definition_id_report_definitions')),
    sa.ForeignKeyConstraint(['requested_by_person_id'], ['persons.id'], name=op.f('fk_generated_reports_requested_by_person_id_persons')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_generated_reports_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_reports'))
    )
    op.create_index(op.f('ix_generated_reports_athlete_profile_id'), 'generated_reports', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_generated_reports_competition_id'), 'generated_reports', ['competition_id'], unique=False)
    op.create_index(op.f('ix_generated_reports_event_id'), 'generated_reports', ['event_id'], unique=False)
    op.create_index(op.f('ix_generated_reports_expires_at'), 'generated_reports', ['expires_at'], unique=False)
    op.create_index(op.f('ix_generated_reports_organization_id'), 'generated_reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_generated_reports_output_format'), 'generated_reports', ['output_format'], unique=False)
    op.create_index(op.f('ix_generated_reports_period_end'), 'generated_reports', ['period_end'], unique=False)
    op.create_index(op.f('ix_generated_reports_period_start'), 'generated_reports', ['period_start'], unique=False)
    op.create_index(op.f('ix_generated_reports_report_definition_id'), 'generated_reports', ['report_definition_id'], unique=False)
    op.create_index(op.f('ix_generated_reports_shared_token'), 'generated_reports', ['shared_token'], unique=True)
    op.create_index(op.f('ix_generated_reports_status'), 'generated_reports', ['status'], unique=False)
    op.create_index(op.f('ix_generated_reports_team_id'), 'generated_reports', ['team_id'], unique=False)
    op.create_index(op.f('ix_generated_reports_title'), 'generated_reports', ['title'], unique=False)
    op.create_table('intelligence_insights',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('athlete_profile_id', app.models.base.GUID(), nullable=True),
    sa.Column('team_id', app.models.base.GUID(), nullable=True),
    sa.Column('event_id', app.models.base.GUID(), nullable=True),
    sa.Column('agent_id', app.models.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('insight_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.Enum('info', 'watch', 'warning', 'critical', name='insightseverity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('new', 'acknowledged', 'actioned', 'dismissed', name='insightstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('reviewed_by_person_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_intelligence_insights_agent_id_agents')),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], name=op.f('fk_intelligence_insights_athlete_profile_id_athlete_profiles')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_intelligence_insights_event_id_events')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_intelligence_insights_organization_id_organizations')),
    sa.ForeignKeyConstraint(['reviewed_by_person_id'], ['persons.id'], name=op.f('fk_intelligence_insights_reviewed_by_person_id_persons')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_intelligence_insights_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intelligence_insights'))
    )
    op.create_index(op.f('ix_intelligence_insights_agent_id'), 'intelligence_insights', ['agent_id'], unique=False)
    op.create_index(op.f('ix_intelligence_insights_athlete_profile_id'), 'intelligence_insights', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_intelligence_insights_event_id'), 'intelligence_insights', ['event_id'], unique=False)
    op.create_index(op.f('ix_intelligence_insights_insight_type'), 'intelligence_insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_intelligence_insights_organization_id'), 'intelligence_insights', ['organization_id'], unique=False)
    op.create_index(op.f('ix_intelligence_insights_severity'), 'intelligence_insights', ['severity'], unique=False)
    op.create_index(op.f('ix_intelligence_insights_status'), 'intelligence_insights', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_insights_team_id'), 'intelligence_insights', ['team_id'], unique=False)
    op.create_index(op.f('ix_intelligence_insights_title'), 'intelligence_insights', ['title'], unique=False)
    op.create_table('report_export_jobs',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('generated_report_id', app.models.base.GUID(), nullable=False),
    sa.Column('output_format', sa.Enum('online', 'pdf', 'excel', 'csv', 'api', name='reportformat', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('destination', sa.String(length=500), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'ready', 'failed', name='reportrunstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_report_id'], ['generated_reports.id'], name=op.f('fk_report_export_jobs_generated_report_id_generated_reports')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_report_export_jobs_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_export_jobs'))
    )
    op.create_index(op.f('ix_report_export_jobs_completed_at'), 'report_export_jobs', ['completed_at'], unique=False)
    op.create_index(op.f('ix_report_export_jobs_generated_report_id'), 'report_export_jobs', ['generated_report_id'], unique=False)
    op.create_index(op.f('ix_report_export_jobs_organization_id'), 'report_export_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_report_export_jobs_output_format'), 'report_export_jobs', ['output_format'], unique=False)
    op.create_index(op.f('ix_report_export_jobs_status'), 'report_export_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_export_jobs_status'), table_name='report_export_jobs')
    op.drop_index(op.f('ix_report_export_jobs_output_format'), table_name='report_export_jobs')
    op.drop_index(op.f('ix_report_export_jobs_organization_id'), table_name='report_export_jobs')
    op.drop_index(op.f('ix_report_export_jobs_generated_report_id'), table_name='report_export_jobs')
    op.drop_index(op.f('ix_report_export_jobs_completed_at'), table_name='report_export_jobs')
    op.drop_table('report_export_jobs')
    op.drop_index(op.f('ix_intelligence_insights_title'), table_name='intelligence_insights')
    op.drop_index(op.f('ix_intelligence_insights_team_id'), table_name='intelligence_insights')
    op.drop_index(op.f('ix_intelligence_insights_status'), table_name='intelligence_insights')
    op.drop_index(op.f('ix_intelligence_insights_severity'), table_name='intelligence_insights')
    op.drop_index(op.f('ix_intelligence_insights_organization_id'), table_name='intelligence_insights')
    op.drop_index(op.f('ix_intelligence_insights_insight_type'), table_name='intelligence_insights')
    op.drop_index(op.f('ix_intelligence_insights_event_id'), table_name='intelligence_insights')
    op.drop_index(op.f('ix_intelligence_insights_athlete_profile_id'), table_name='intelligence_insights')
    op.drop_index(op.f('ix_intelligence_insights_agent_id'), table_name='intelligence_insights')
    op.drop_table('intelligence_insights')
    op.drop_index(op.f('ix_generated_reports_title'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_team_id'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_status'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_shared_token'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_report_definition_id'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_period_start'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_period_end'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_output_format'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_organization_id'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_expires_at'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_event_id'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_competition_id'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_athlete_profile_id'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_scheduled_reports_status'), table_name='scheduled_reports')
    op.drop_index(op.f('ix_scheduled_reports_report_definition_id'), table_name='scheduled_reports')
    op.drop_index(op.f('ix_scheduled_reports_organization_id'), table_name='scheduled_reports')
    op.drop_index(op.f('ix_scheduled_reports_next_run_at'), table_name='scheduled_reports')
    op.drop_index(op.f('ix_scheduled_reports_name'), table_name='scheduled_reports')
    op.drop_index(op.f('ix_scheduled_reports_last_run_at'), table_name='scheduled_reports')
    op.drop_index(op.f('ix_scheduled_reports_frequency'), table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    op.drop_index(op.f('ix_predictive_risk_scores_valid_for_date'), table_name='predictive_risk_scores')
    op.drop_index(op.f('ix_predictive_risk_scores_score'), table_name='predictive_risk_scores')
    op.drop_index(op.f('ix_predictive_risk_scores_risk_band'), table_name='predictive_risk_scores')
    op.drop_index(op.f('ix_predictive_risk_scores_organization_id'), table_name='predictive_risk_scores')
    op.drop_index(op.f('ix_predictive_risk_scores_model_name'), table_name='predictive_risk_scores')
    op.drop_index(op.f('ix_predictive_risk_scores_athlete_profile_id'), table_name='predictive_risk_scores')
    op.drop_table('predictive_risk_scores')
    op.drop_index(op.f('ix_report_definitions_status'), table_name='report_definitions')
    op.drop_index(op.f('ix_report_definitions_organization_id'), table_name='report_definitions')
    op.drop_index(op.f('ix_report_definitions_name'), table_name='report_definitions')
    op.drop_index(op.f('ix_report_definitions_default_format'), table_name='report_definitions')
    op.drop_index(op.f('ix_report_definitions_category'), table_name='report_definitions')
    op.drop_table('report_definitions')
    # ### end Alembic commands ###
