"""add training plans and sessions

Revision ID: b23079d70437
Revises: dea9ca28416e
Create Date: 2026-05-27 05:45:04.167618
"""

from collections.abc import Sequence

import app.models.base
import sqlalchemy as sa
from alembic import op



revision: str = "b23079d70437"
down_revision: str | None = "dea9ca28416e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_drills',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('sport', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('focus_area', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('coaching_points', sa.Text(), nullable=True),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('default_intensity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_training_drills_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_drills'))
    )
    op.create_index(op.f('ix_training_drills_category'), 'training_drills', ['category'], unique=False)
    op.create_index(op.f('ix_training_drills_focus_area'), 'training_drills', ['focus_area'], unique=False)
    op.create_index(op.f('ix_training_drills_name'), 'training_drills', ['name'], unique=False)
    op.create_index(op.f('ix_training_drills_organization_id'), 'training_drills', ['organization_id'], unique=False)
    op.create_index(op.f('ix_training_drills_sport'), 'training_drills', ['sport'], unique=False)
    op.create_index(op.f('ix_training_drills_status'), 'training_drills', ['status'], unique=False)
    op.create_table('training_plans',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('team_id', app.models.base.GUID(), nullable=True),
    sa.Column('athlete_profile_id', app.models.base.GUID(), nullable=True),
    sa.Column('created_by_person_id', app.models.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('focus_area', sa.String(length=160), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', 'archived', name='trainingplanstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('source_summary', sa.Text(), nullable=True),
    sa.Column('load_guidance', sa.Text(), nullable=True),
    sa.Column('recovery_protocol', sa.Text(), nullable=True),
    sa.Column('progress_checkpoints', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], name=op.f('fk_training_plans_athlete_profile_id_athlete_profiles')),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['persons.id'], name=op.f('fk_training_plans_created_by_person_id_persons')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_training_plans_organization_id_organizations')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_training_plans_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_plans'))
    )
    op.create_index(op.f('ix_training_plans_athlete_profile_id'), 'training_plans', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_training_plans_focus_area'), 'training_plans', ['focus_area'], unique=False)
    op.create_index(op.f('ix_training_plans_organization_id'), 'training_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_training_plans_period_end'), 'training_plans', ['period_end'], unique=False)
    op.create_index(op.f('ix_training_plans_period_start'), 'training_plans', ['period_start'], unique=False)
    op.create_index(op.f('ix_training_plans_status'), 'training_plans', ['status'], unique=False)
    op.create_index(op.f('ix_training_plans_team_id'), 'training_plans', ['team_id'], unique=False)
    op.create_index(op.f('ix_training_plans_title'), 'training_plans', ['title'], unique=False)
    op.create_table('training_plan_items',
    sa.Column('plan_id', app.models.base.GUID(), nullable=False),
    sa.Column('drill_id', app.models.base.GUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('day_label', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('focus_area', sa.String(length=120), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drill_id'], ['training_drills.id'], name=op.f('fk_training_plan_items_drill_id_training_drills')),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], name=op.f('fk_training_plan_items_plan_id_training_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_plan_items'))
    )
    op.create_index(op.f('ix_training_plan_items_plan_id'), 'training_plan_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_training_plan_items_sequence'), 'training_plan_items', ['sequence'], unique=False)
    op.create_table('training_session_plans',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('team_id', app.models.base.GUID(), nullable=False),
    sa.Column('plan_id', app.models.base.GUID(), nullable=True),
    sa.Column('event_id', app.models.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('rpe_target', sa.Integer(), nullable=False),
    sa.Column('load_score', sa.Float(), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='trainingsessionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_training_session_plans_event_id_events')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_training_session_plans_organization_id_organizations')),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], name=op.f('fk_training_session_plans_plan_id_training_plans')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_training_session_plans_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_session_plans'))
    )
    op.create_index(op.f('ix_training_session_plans_event_id'), 'training_session_plans', ['event_id'], unique=False)
    op.create_index(op.f('ix_training_session_plans_load_score'), 'training_session_plans', ['load_score'], unique=False)
    op.create_index(op.f('ix_training_session_plans_organization_id'), 'training_session_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_training_session_plans_plan_id'), 'training_session_plans', ['plan_id'], unique=False)
    op.create_index(op.f('ix_training_session_plans_scheduled_for'), 'training_session_plans', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_training_session_plans_status'), 'training_session_plans', ['status'], unique=False)
    op.create_index(op.f('ix_training_session_plans_team_id'), 'training_session_plans', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_session_plans_team_id'), table_name='training_session_plans')
    op.drop_index(op.f('ix_training_session_plans_status'), table_name='training_session_plans')
    op.drop_index(op.f('ix_training_session_plans_scheduled_for'), table_name='training_session_plans')
    op.drop_index(op.f('ix_training_session_plans_plan_id'), table_name='training_session_plans')
    op.drop_index(op.f('ix_training_session_plans_organization_id'), table_name='training_session_plans')
    op.drop_index(op.f('ix_training_session_plans_load_score'), table_name='training_session_plans')
    op.drop_index(op.f('ix_training_session_plans_event_id'), table_name='training_session_plans')
    op.drop_table('training_session_plans')
    op.drop_index(op.f('ix_training_plan_items_sequence'), table_name='training_plan_items')
    op.drop_index(op.f('ix_training_plan_items_plan_id'), table_name='training_plan_items')
    op.drop_table('training_plan_items')
    op.drop_index(op.f('ix_training_plans_title'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_team_id'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_status'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_period_start'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_period_end'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_organization_id'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_focus_area'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_athlete_profile_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_training_drills_status'), table_name='training_drills')
    op.drop_index(op.f('ix_training_drills_sport'), table_name='training_drills')
    op.drop_index(op.f('ix_training_drills_organization_id'), table_name='training_drills')
    op.drop_index(op.f('ix_training_drills_name'), table_name='training_drills')
    op.drop_index(op.f('ix_training_drills_focus_area'), table_name='training_drills')
    op.drop_index(op.f('ix_training_drills_category'), table_name='training_drills')
    op.drop_table('training_drills')
    # ### end Alembic commands ###
