"""add performance metrics and assessments

Revision ID: dea9ca28416e
Revises: 6138f95a6b16
Create Date: 2026-05-27 05:26:50.793487
"""

from collections.abc import Sequence

import app.models.base
import sqlalchemy as sa
from alembic import op


revision: str = "dea9ca28416e"
down_revision: str | None = "6138f95a6b16"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_metric_definitions',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('sport', sa.String(length=80), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('category', sa.Enum('physical', 'technical', 'tactical', 'mental', 'wellness', 'competition', name='metriccategory', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('higher_is_better', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_performance_metric_definitions_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_metric_definitions')),
    sa.UniqueConstraint('organization_id', 'sport', 'code', name='uq_performance_metric_definitions_org_sport_code')
    )
    op.create_index(op.f('ix_performance_metric_definitions_category'), 'performance_metric_definitions', ['category'], unique=False)
    op.create_index(op.f('ix_performance_metric_definitions_code'), 'performance_metric_definitions', ['code'], unique=False)
    op.create_index(op.f('ix_performance_metric_definitions_organization_id'), 'performance_metric_definitions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_performance_metric_definitions_sport'), 'performance_metric_definitions', ['sport'], unique=False)
    op.create_index(op.f('ix_performance_metric_definitions_status'), 'performance_metric_definitions', ['status'], unique=False)
    op.create_table('athlete_assessments',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('athlete_profile_id', app.models.base.GUID(), nullable=False),
    sa.Column('event_id', app.models.base.GUID(), nullable=True),
    sa.Column('assessed_by_person_id', app.models.base.GUID(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.Column('physical_score', sa.Float(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('tactical_score', sa.Float(), nullable=False),
    sa.Column('mental_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('pending_review', 'verified', 'rejected', name='metricverificationstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by_person_id'], ['persons.id'], name=op.f('fk_athlete_assessments_assessed_by_person_id_persons')),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], name=op.f('fk_athlete_assessments_athlete_profile_id_athlete_profiles')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_athlete_assessments_event_id_events')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_athlete_assessments_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete_assessments'))
    )
    op.create_index(op.f('ix_athlete_assessments_assessed_at'), 'athlete_assessments', ['assessed_at'], unique=False)
    op.create_index(op.f('ix_athlete_assessments_athlete_profile_id'), 'athlete_assessments', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_athlete_assessments_event_id'), 'athlete_assessments', ['event_id'], unique=False)
    op.create_index(op.f('ix_athlete_assessments_organization_id'), 'athlete_assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_athlete_assessments_overall_score'), 'athlete_assessments', ['overall_score'], unique=False)
    op.create_index(op.f('ix_athlete_assessments_verification_status'), 'athlete_assessments', ['verification_status'], unique=False)
    op.create_table('athlete_performance_observations',
    sa.Column('organization_id', app.models.base.GUID(), nullable=False),
    sa.Column('athlete_profile_id', app.models.base.GUID(), nullable=False),
    sa.Column('metric_definition_id', app.models.base.GUID(), nullable=False),
    sa.Column('event_id', app.models.base.GUID(), nullable=True),
    sa.Column('recorded_by_person_id', app.models.base.GUID(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('raw_value', sa.String(length=160), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'coach_evaluation', 'self_assessment', 'official_stats', 'video_analysis', 'audio_narration', 'wearable', 'agent_extracted', name='metricsource', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.Enum('pending_review', 'verified', 'rejected', name='metricverificationstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], name=op.f('fk_athlete_performance_observations_athlete_profile_id_athlete_profiles')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_athlete_performance_observations_event_id_events')),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['performance_metric_definitions.id'], name=op.f('fk_athlete_performance_observations_metric_definition_id_performance_metric_definitions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_athlete_performance_observations_organization_id_organizations')),
    sa.ForeignKeyConstraint(['recorded_by_person_id'], ['persons.id'], name=op.f('fk_athlete_performance_observations_recorded_by_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete_performance_observations'))
    )
    op.create_index(op.f('ix_athlete_performance_observations_athlete_profile_id'), 'athlete_performance_observations', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_athlete_performance_observations_event_id'), 'athlete_performance_observations', ['event_id'], unique=False)
    op.create_index(op.f('ix_athlete_performance_observations_metric_definition_id'), 'athlete_performance_observations', ['metric_definition_id'], unique=False)
    op.create_index(op.f('ix_athlete_performance_observations_observed_at'), 'athlete_performance_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_athlete_performance_observations_organization_id'), 'athlete_performance_observations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_athlete_performance_observations_source'), 'athlete_performance_observations', ['source'], unique=False)
    op.create_index(op.f('ix_athlete_performance_observations_verification_status'), 'athlete_performance_observations', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_athlete_performance_observations_verification_status'), table_name='athlete_performance_observations')
    op.drop_index(op.f('ix_athlete_performance_observations_source'), table_name='athlete_performance_observations')
    op.drop_index(op.f('ix_athlete_performance_observations_organization_id'), table_name='athlete_performance_observations')
    op.drop_index(op.f('ix_athlete_performance_observations_observed_at'), table_name='athlete_performance_observations')
    op.drop_index(op.f('ix_athlete_performance_observations_metric_definition_id'), table_name='athlete_performance_observations')
    op.drop_index(op.f('ix_athlete_performance_observations_event_id'), table_name='athlete_performance_observations')
    op.drop_index(op.f('ix_athlete_performance_observations_athlete_profile_id'), table_name='athlete_performance_observations')
    op.drop_table('athlete_performance_observations')
    op.drop_index(op.f('ix_athlete_assessments_verification_status'), table_name='athlete_assessments')
    op.drop_index(op.f('ix_athlete_assessments_overall_score'), table_name='athlete_assessments')
    op.drop_index(op.f('ix_athlete_assessments_organization_id'), table_name='athlete_assessments')
    op.drop_index(op.f('ix_athlete_assessments_event_id'), table_name='athlete_assessments')
    op.drop_index(op.f('ix_athlete_assessments_athlete_profile_id'), table_name='athlete_assessments')
    op.drop_index(op.f('ix_athlete_assessments_assessed_at'), table_name='athlete_assessments')
    op.drop_table('athlete_assessments')
    op.drop_index(op.f('ix_performance_metric_definitions_status'), table_name='performance_metric_definitions')
    op.drop_index(op.f('ix_performance_metric_definitions_sport'), table_name='performance_metric_definitions')
    op.drop_index(op.f('ix_performance_metric_definitions_organization_id'), table_name='performance_metric_definitions')
    op.drop_index(op.f('ix_performance_metric_definitions_code'), table_name='performance_metric_definitions')
    op.drop_index(op.f('ix_performance_metric_definitions_category'), table_name='performance_metric_definitions')
    op.drop_table('performance_metric_definitions')
    # ### end Alembic commands ###
