from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND_DIR = REPO_ROOT / "backend"
TS_OUTPUT = REPO_ROOT / "packages" / "sdk-typescript" / "src" / "generated" / "sdk-endpoints.ts"
PY_OUTPUT = REPO_ROOT / "packages" / "sdk-python" / "src" / "afrolete_sdk" / "endpoints.py"


def endpoint_catalog() -> list[dict[str, object]]:
    sys.path.insert(0, str(BACKEND_DIR))
    from app.services.developer import developer_sdk_endpoint_catalog

    return [
        endpoint.model_dump(mode="json")
        for endpoint in developer_sdk_endpoint_catalog()
    ]


def typescript_content(endpoints: list[dict[str, object]]) -> str:
    return "\n".join(
        [
            "// Generated by scripts/generate_sdk_endpoint_manifest.py; do not edit by hand.",
            "",
            "export interface AfroLeteSdkEndpoint {",
            "  method: string;",
            "  path: string;",
            "  category: string;",
            "  summary: string;",
            "  required_scopes: readonly string[];",
            "  typescript_entry_point: string | null;",
            "  python_entry_point: string | null;",
            "  webhook_events: readonly string[];",
            "}",
            "",
            "export const AFROLETE_SDK_ENDPOINTS =",
            f"{json.dumps(endpoints, indent=2)} as const satisfies readonly AfroLeteSdkEndpoint[];",
            "",
        ]
    )


def python_content(endpoints: list[dict[str, object]]) -> str:
    return "\n".join(
        [
            '"""Generated SDK endpoint manifest for AfroLete developer clients."""',
            "",
            "# Generated by scripts/generate_sdk_endpoint_manifest.py; do not edit by hand.",
            "",
            "from __future__ import annotations",
            "",
            "from typing import Any",
            "",
            f"AFROLETE_SDK_ENDPOINTS: tuple[dict[str, Any], ...] = tuple({json.dumps(endpoints, indent=2)})",
            "",
            "__all__ = [\"AFROLETE_SDK_ENDPOINTS\"]",
            "",
        ]
    )


def assert_current(path: Path, expected: str) -> None:
    if not path.exists() or path.read_text() != expected:
        raise SystemExit(f"{path.relative_to(REPO_ROOT)} is out of date; rerun this generator")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SDK endpoint manifests from the backend catalog.")
    parser.add_argument("--check", action="store_true", help="Fail if generated manifests are stale.")
    args = parser.parse_args()
    endpoints = endpoint_catalog()
    ts_content = typescript_content(endpoints)
    py_content = python_content(endpoints)
    if args.check:
        assert_current(TS_OUTPUT, ts_content)
        assert_current(PY_OUTPUT, py_content)
        print(f"Verified {len(endpoints)} generated SDK endpoint definitions.")
        return
    TS_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUTPUT.write_text(ts_content)
    PY_OUTPUT.write_text(py_content)
    print(f"Generated {len(endpoints)} SDK endpoint definitions.")


if __name__ == "__main__":
    main()
